/**
 * Iranian Castles Database
 * Curated bilingual dataset of historic castles and fortresses of Iran.
 * Used for generating unique session names in Cipher.
 *
 * Source: https://fa.wikipedia.org/wiki/فهرست_قلعه‌های_ایران
 */

const LIST_PAGE = 'https://fa.wikipedia.org/wiki/%D9%81%D9%87%D8%B1%D8%B3%D8%AA_%D9%82%D9%84%D8%B9%D9%87%E2%80%8C%D9%87%D8%A7%DB%8C_%D8%A7%DB%8C%D8%B1%D8%A7%D9%86';

export interface IranCastle {
  nameFa: string;
  nameEn: string;
  province: string;
  descFa: string;
  descEn: string;
  wiki: string;
}

export const IRAN_CASTLES: IranCastle[] = [
  /* ======== TIER 1 — Major landmarks (richer descriptions) ======== */
  {
    nameFa: 'ارگ بم',
    nameEn: 'Arg-e Bam',
    province: 'Kerman',
    descFa: 'ارگ بم بزرگ‌ترین سازه خشتی جهان است که در شهر بم واقع شده و قدمتی بیش از ۲۰۰۰ سال دارد. این بنای عظیم در سال ۲۰۰۴ در فهرست میراث جهانی یونسکو ثبت شد. زلزله ۱۳۸۲ آسیب سنگینی به آن وارد کرد اما بازسازی گسترده‌ای در حال انجام است.',
    descEn: 'Arg-e Bam is the largest adobe structure in the world, located in Kerman province with over 2,000 years of history. It was inscribed as a UNESCO World Heritage Site in 2004. The 2003 earthquake caused severe damage, but extensive restoration is ongoing.',
    wiki: 'https://en.wikipedia.org/wiki/Arg-e_Bam',
  },
  {
    nameFa: 'قلعه الموت',
    nameEn: 'Alamut Castle',
    province: 'Qazvin',
    descFa: 'قلعه الموت در ارتفاعات البرز واقع شده و مقر حسن صباح، رهبر فرقه اسماعیلیه نزاری بود. این دژ کوهستانی در قرن یازدهم میلادی به دست اسماعیلیان افتاد و کتابخانه بزرگی داشت که در حمله مغول ویران شد.',
    descEn: 'Alamut Castle is a mountain fortress in the Alborz range, famous as the stronghold of Hassan-i Sabbah and the Nizari Ismaili order. Captured in the 11th century, it housed a great library destroyed during the Mongol invasion of 1256.',
    wiki: 'https://en.wikipedia.org/wiki/Alamut_Castle',
  },
  {
    nameFa: 'قلعه فلک‌الافلاک',
    nameEn: 'Falak-ol-Aflak Castle',
    province: 'Lorestan',
    descFa: 'قلعه فلک‌الافلاک در شهر خرم‌آباد بر فراز تپه‌ای مشرف به شهر بنا شده و از دوره ساسانی به جا مانده است. این دژ هشت برج بلند دارد و امروزه به عنوان موزه استفاده می‌شود.',
    descEn: 'Falak-ol-Aflak is a Sasanian-era fortress towering over Khorramabad on a prominent hill. With eight massive towers and thick walls, it now serves as an archaeological museum and is one of Iran\'s most iconic castles.',
    wiki: 'https://en.wikipedia.org/wiki/Falak-ol-Aflak_Castle',
  },
  {
    nameFa: 'قلعه رودخان',
    nameEn: 'Rudkhan Castle',
    province: 'Gilan',
    descFa: 'قلعه رودخان در جنگل‌های گیلان واقع شده و یکی از بزرگ‌ترین قلعه‌های آجری ایران است. این دژ با بیش از ۶۵ برج و دیوارهایی به طول ۱۵۰۰ متر در دل جنگل‌های سرسبز ساخته شده است.',
    descEn: 'Rudkhan Castle is one of Iran\'s largest brick-and-stone fortresses, nestled in the lush forests of Gilan. It features over 65 towers and 1,500 meters of walls winding through the dense woodland.',
    wiki: 'https://en.wikipedia.org/wiki/Rudkhan_Castle',
  },
  {
    nameFa: 'ارگ کریم‌خان',
    nameEn: 'Arg of Karim Khan',
    province: 'Fars',
    descFa: 'ارگ کریم‌خان زند در مرکز شهر شیراز قرار دارد و در دوره زندیه به فرمان کریم‌خان ساخته شده است. این بنا چهار برج دایره‌ای بلند دارد و زمانی مقر حکومتی بوده است.',
    descEn: 'The Arg of Karim Khan is a citadel built during the Zand dynasty in central Shiraz. Featuring four circular towers and a large courtyard, it served as the royal residence of Karim Khan and later as a prison in the Qajar era.',
    wiki: 'https://en.wikipedia.org/wiki/Arg_of_Karim_Khan',
  },
  {
    nameFa: 'تخت سلیمان',
    nameEn: 'Takht-e Soleyman',
    province: 'West Azerbaijan',
    descFa: 'تخت سلیمان مجموعه‌ای باستانی شامل آتشکده و دریاچه آتشفشانی در آذربایجان غربی است که در فهرست میراث جهانی یونسکو ثبت شده است. این محل در دوره ساسانی مهم‌ترین مرکز آیینی زرتشتی بود.',
    descEn: 'Takht-e Soleyman is a UNESCO World Heritage archaeological site featuring a Zoroastrian fire temple and a volcanic crater lake. It was the most important Zoroastrian ritual center during the Sasanian period.',
    wiki: 'https://en.wikipedia.org/wiki/Takht-e_Soleyman',
  },
  {
    nameFa: 'ارگ تبریز',
    nameEn: 'Arg of Tabriz',
    province: 'East Azerbaijan',
    descFa: 'ارگ تبریز یا ارک علیشاه از بزرگ‌ترین سازه‌های آجری ایران است که در قرن هشتم هجری ساخته شده است. دیوار باقی‌مانده آن با ارتفاع ۲۸ متر هنوز پابرجاست.',
    descEn: 'The Arg of Tabriz, also known as Ark-e Alishah, is one of Iran\'s largest brick structures, built in the 14th century. Its remaining wall stands 28 meters tall and was once part of a grand mosque and citadel complex.',
    wiki: 'https://en.wikipedia.org/wiki/Arg_of_Tabriz',
  },
  {
    nameFa: 'نارین قلعه',
    nameEn: 'Narin Castle',
    province: 'Yazd',
    descFa: 'نارین قلعه در شهر میبد یزد واقع شده و از قدیمی‌ترین بناهای خشتی ایران محسوب می‌شود. قدمت آن به دوره ساسانیان و حتی پیش از آن بازمی‌گردد.',
    descEn: 'Narin Castle in Meybod, Yazd, is one of Iran\'s oldest adobe structures, dating back to the Sasanian era or earlier. Its multi-layered construction reveals millennia of continuous habitation.',
    wiki: 'https://en.wikipedia.org/wiki/Narin_Castle',
  },
  {
    nameFa: 'قلعه دختر',
    nameEn: 'Dokhtar Castle',
    province: 'Fars',
    descFa: 'قلعه دختر در فیروزآباد فارس از دوره ساسانی به جا مانده و منسوب به اردشیر بابکان است. این دژ بر فراز صخره‌ای مشرف به تنگه ساخته شده است.',
    descEn: 'Dokhtar Castle in Firuzabad is a Sasanian-era fortress attributed to Ardashir I, founder of the Sasanian dynasty. Perched on a rocky cliff overlooking a gorge, it is a masterpiece of early Sasanian military architecture.',
    wiki: 'https://en.wikipedia.org/wiki/Qaleh_Dokhtar',
  },
  {
    nameFa: 'ارگ راین',
    nameEn: 'Arg-e Rayen',
    province: 'Kerman',
    descFa: 'ارگ راین در شهرستان راین کرمان به عنوان دومین بنای بزرگ خشتی ایران شناخته می‌شود. این ارگ قدمتی حدود ۱۵۰۰ ساله دارد و ساختار مشابهی با ارگ بم دارد.',
    descEn: 'Arg-e Rayen is recognized as Iran\'s second-largest adobe citadel, with a structure similar to Arg-e Bam. Located in Kerman province, it is approximately 1,500 years old and remarkably well-preserved.',
    wiki: 'https://en.wikipedia.org/wiki/Arg-e_Rayen',
  },
  {
    nameFa: 'قلعه ایزدخواست',
    nameEn: 'Izadkhast Castle',
    province: 'Fars',
    descFa: 'قلعه ایزدخواست بر فراز صخره‌ای طبیعی در استان فارس ساخته شده و از دوره ساسانی باقی مانده است. مجموعه آن شامل کاروانسرا، حمام و مسجد است.',
    descEn: 'Izadkhast Castle is built atop a dramatic natural rock formation in Fars province. Dating to the Sasanian era, the complex includes a caravanserai, bathhouse, and mosque alongside the fortress.',
    wiki: 'https://en.wikipedia.org/wiki/Izadkhast',
  },
  {
    nameFa: 'قلعه سریزد',
    nameEn: 'Sar Yazd Castle',
    province: 'Yazd',
    descFa: 'قلعه سریزد در استان یزد به عنوان یکی از قدیمی‌ترین صندوق امانات جهان شناخته می‌شود. مردم منطقه اشیای قیمتی خود را در اتاقک‌های امن این دژ نگهداری می‌کردند.',
    descEn: 'Sar Yazd Castle in Yazd province is considered one of the world\'s oldest safe deposit complexes. Locals stored their valuables in its secure chambers, making it a unique communal treasury-fortress.',
    wiki: 'https://en.wikipedia.org/wiki/Sar_Yazd',
  },
  {
    nameFa: 'قلعه پرتغالی‌ها',
    nameEn: 'Portuguese Castle',
    province: 'Hormozgan',
    descFa: 'قلعه پرتغالی‌ها در جزیره هرمز توسط پرتغالی‌ها در قرن شانزدهم میلادی ساخته شد. این قلعه ساحلی از سنگ‌های مرجانی قرمز ساخته شده و نمایانگر دوره استعمار پرتغال در خلیج فارس است.',
    descEn: 'The Portuguese Castle on Hormuz Island was built by the Portuguese in the 16th century from distinctive red coral stone. It stands as a vivid reminder of the Portuguese colonial presence in the Persian Gulf.',
    wiki: 'https://en.wikipedia.org/wiki/Portuguese_Castle_(Hormuz)',
  },
  {
    nameFa: 'ارگ بلقیس',
    nameEn: 'Belqeys Citadel',
    province: 'North Khorasan',
    descFa: 'ارگ بلقیس در اسفراین خراسان شمالی از بناهای مهم ساسانی و اسلامی است. این مجموعه شهری شامل حصار، بازار و مسجد بوده و از بزرگ‌ترین شهرهای تاریخی خراسان محسوب می‌شود.',
    descEn: 'Belqeys Citadel near Esfarayen is a major Sasanian and Islamic archaeological complex. Once a thriving city with walls, bazaars, and mosques, it is one of the largest historic urban sites in Khorasan.',
    wiki: 'https://en.wikipedia.org/wiki/Belqeys',
  },
  {
    nameFa: 'قلعه ایرج',
    nameEn: 'Iraj Castle',
    province: 'Tehran',
    descFa: 'قلعه ایرج در پیشوای ورامین واقع شده و ممکن است بزرگ‌ترین قلعه خشتی جنوب غربی آسیا باشد. قدمت آن به دوره ساسانی بازمی‌گردد و محوطه‌ای عظیم دارد.',
    descEn: 'Iraj Castle near Pishva is possibly the largest ancient fortress in southwest Asia. Dating to the Sasanian period, its vast archaeological site covers an immense area in the Tehran province flatlands.',
    wiki: 'https://en.wikipedia.org/wiki/Qaleh_Iraj',
  },
  {
    nameFa: 'قلعه لمبسر',
    nameEn: 'Lambsar Castle',
    province: 'Qazvin',
    descFa: 'قلعه لمبسر یکی از مهم‌ترین دژهای اسماعیلیه در رشته‌کوه البرز است. این قلعه به عنوان زندان و انبار سلاح اسماعیلیان استفاده می‌شد و پس از الموت، دومین قلعه مهم آنان بود.',
    descEn: 'Lambsar Castle is one of the most important Ismaili fortresses in the Alborz range. It served as the Ismaili armory and prison, and was their second-most strategic stronghold after Alamut.',
    wiki: 'https://en.wikipedia.org/wiki/Lambsar',
  },
  {
    nameFa: 'قلعه جمهور',
    nameEn: 'Babak Fort',
    province: 'East Azerbaijan',
    descFa: 'قلعه جمهور یا قلعه بابک بر فراز کوهی صعب‌العبور در کلیبر آذربایجان شرقی واقع شده و محل قیام بابک خرمدین علیه خلافت عباسی در قرن نهم میلادی بود.',
    descEn: 'Babak Fort (Qaleh Jomhur) sits atop a rugged mountain in Kaleybar, East Azerbaijan. It was the stronghold of Babak Khorramdin during his uprising against the Abbasid Caliphate in the 9th century.',
    wiki: 'https://en.wikipedia.org/wiki/Babak_Fort',
  },
  {
    nameFa: 'قلعه ضحاک',
    nameEn: 'Zahhak Castle',
    province: 'East Azerbaijan',
    descFa: 'قلعه ضحاک در هشترود آذربایجان شرقی واقع شده و نام خود را از ضحاک اسطوره‌ای شاهنامه گرفته است. این دژ بر فراز صخره‌ای طبیعی ساخته شده و قدمت آن به هزاره اول قبل از میلاد بازمی‌گردد.',
    descEn: 'Zahhak Castle in Hashtrud is named after the mythical tyrant Zahhak from the Shahnameh. Built on a natural rock outcrop, it dates back to the first millennium BCE and offers panoramic views of the valley.',
    wiki: 'https://en.wikipedia.org/wiki/Zahhak_Castle',
  },
  {
    nameFa: 'قلعه سام',
    nameEn: 'Sam Castle',
    province: 'Sistan & Baluchestan',
    descFa: 'قلعه سام قدیمی‌ترین ارگ خشتی سیستان و بلوچستان است و در نزدیکی زابل واقع شده. از دوره اشکانی باقی مانده و نام خود را از سام، پهلوان شاهنامه گرفته است.',
    descEn: 'Sam Castle is the oldest adobe citadel in Sistan & Baluchestan, located near Zabol. Dating to the Parthian era, it is named after Sam, the legendary hero from the Shahnameh epic.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%B3%D8%A7%D9%85',
  },

  /* ======== TIER 2 — Notable castles (brief descriptions) ======== */
  {
    nameFa: 'قلعه چهریق',
    nameEn: 'Chehrig Castle',
    province: 'West Azerbaijan',
    descFa: 'دژی تاریخی در سلماس که محل زندان باب، بنیان‌گذار آیین بابی بود.',
    descEn: 'A historic fortress in Salmas, known as the prison of the Báb, founder of Bábism.',
    wiki: 'https://en.wikipedia.org/wiki/Chehrig_Castle',
  },
  {
    nameFa: 'قلعه قهقهه',
    nameEn: 'Qahqaheh Castle',
    province: 'Ardabil',
    descFa: 'دژ کوهستانی در مشگین‌شهر که در دوره‌های مختلف تاریخی مورد استفاده قرار گرفته است.',
    descEn: 'A mountain fortress near Meshginshahr used across multiple historical periods.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D9%82%D9%87%D9%82%D9%87%D9%87',
  },
  {
    nameFa: 'قلعه بیاضه',
    nameEn: 'Bayazeh Castle',
    province: 'Isfahan',
    descFa: 'دژ خشتی قدیمی در شرق اصفهان با قدمت ساسانی.',
    descEn: 'An ancient adobe fortress in eastern Isfahan dating to the Sasanian era.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%A8%DB%8C%D8%A7%D8%B6%D9%87',
  },
  {
    nameFa: 'ارگ گوگد',
    nameEn: 'Googad Citadel',
    province: 'Isfahan',
    descFa: 'ارگ تاریخی در شهرستان گلپایگان اصفهان.',
    descEn: 'A historic citadel in Golpayegan, Isfahan province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D8%A7%D8%B1%DA%AF_%DA%AF%D9%88%DA%AF%D8%AF',
  },
  {
    nameFa: 'قلعه والی',
    nameEn: 'Vali Castle',
    province: 'Ilam',
    descFa: 'قلعه‌ای قاجاری در شهر ایلام که زمانی مقر والیان پشتکوه بوده است.',
    descEn: 'A Qajar-era castle in Ilam city, once the seat of the Pushtikooh governors.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D9%88%D8%A7%D9%84%DB%8C',
  },
  {
    nameFa: 'قلعه سلاسل',
    nameEn: 'Salasil Castle',
    province: 'Khuzestan',
    descFa: 'دژ باستانی شوشتر در خوزستان که نام آن به معنی زنجیرها است.',
    descEn: 'An ancient fortress in Shushtar, Khuzestan, whose name means "chains."',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%B3%D9%84%D8%A7%D8%B3%D9%84',
  },
  {
    nameFa: 'قلعه دم‌دم',
    nameEn: 'Dam Dam Castle',
    province: 'West Azerbaijan',
    descFa: 'دژ کوهستانی در ارومیه که در قرن هفدهم میلادی شاهد محاصره‌ای معروف بود.',
    descEn: 'A mountain fortress near Urmia, site of a famous 17th-century siege.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%AF%D9%85_%D8%AF%D9%85',
  },
  {
    nameFa: 'دژ برازجان',
    nameEn: 'Borazjan Fortress',
    province: 'Bushehr',
    descFa: 'محوطه باستانی هخامنشی در بوشهر.',
    descEn: 'An Achaemenid archaeological site in Bushehr province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D8%AF%DA%98_%D8%A8%D8%B1%D8%A7%D8%B2%D8%AC%D8%A7%D9%86',
  },
  {
    nameFa: 'قلعه هلندی‌ها',
    nameEn: 'Dutch Castle',
    province: 'Bushehr',
    descFa: 'دژی ساخته شده توسط کمپانی هند شرقی هلند در سواحل بوشهر.',
    descEn: 'A fortress built by the Dutch East India Company on the Bushehr coast.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D9%87%D9%84%D9%86%D8%AF%DB%8C%E2%80%8C%D9%87%D8%A7',
  },
  {
    nameFa: 'برج طغرل',
    nameEn: 'Toghrol Tower',
    province: 'Tehran',
    descFa: 'برج آرامگاهی سلجوقی در شهر ری با معماری منحصربه‌فرد.',
    descEn: 'A Seljuk-era funerary tower in Rey with distinctive architecture.',
    wiki: 'https://en.wikipedia.org/wiki/Toghrol_Tower',
  },
  {
    nameFa: 'قلعه طبرک',
    nameEn: 'Tabarak Castle',
    province: 'Tehran',
    descFa: 'حصار و بارو قدیم تهران از دوره صفویه.',
    descEn: 'The old rampart and fortification wall of Tehran from the Safavid period.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%B7%D8%A8%D8%B1%DA%A9',
  },
  {
    nameFa: 'قلعه دزک',
    nameEn: 'Dezak Castle',
    province: 'Chaharmahal & Bakhtiari',
    descFa: 'دژ تاریخی در چهارمحال و بختیاری.',
    descEn: 'A historic fortress in Chaharmahal & Bakhtiari province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%AF%D8%B2%DA%A9',
  },
  {
    nameFa: 'قلعه چالشتر',
    nameEn: 'Chaleshtor Castle',
    province: 'Chaharmahal & Bakhtiari',
    descFa: 'قلعه‌ای زیبا متعلق به دوره صفویه در چهارمحال و بختیاری.',
    descEn: 'A beautiful Safavid-era castle in Chaharmahal & Bakhtiari province.',
    wiki: 'https://en.wikipedia.org/wiki/Chaleshtor_Castle',
  },
  {
    nameFa: 'ارگ طبس',
    nameEn: 'Arg-e Tabas',
    province: 'South Khorasan',
    descFa: 'ارگ تاریخی شهر طبس در خراسان جنوبی.',
    descEn: 'The historic citadel of Tabas in South Khorasan province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D8%A7%D8%B1%DA%AF_%D8%B7%D8%A8%D8%B3',
  },
  {
    nameFa: 'قلعه بیرجند',
    nameEn: 'Birjand Castle',
    province: 'South Khorasan',
    descFa: 'قلعه‌ای تاریخی در مرکز شهر بیرجند.',
    descEn: 'A historic castle in the center of Birjand city.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%A8%DB%8C%D8%B1%D8%AC%D9%86%D8%AF',
  },
  {
    nameFa: 'قلعه فورگ',
    nameEn: 'Furg Castle',
    province: 'South Khorasan',
    descFa: 'دژ خشتی تاریخی در فورگ خراسان جنوبی.',
    descEn: 'A historic adobe fortress in Furg, South Khorasan.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D9%81%D9%88%D8%B1%DA%AF',
  },
  {
    nameFa: 'قلعه رستم',
    nameEn: 'Rostam Castle',
    province: 'Sistan & Baluchestan',
    descFa: 'دژ باستانی در سیستان منسوب به رستم پهلوان شاهنامه.',
    descEn: 'An ancient fortress in Sistan attributed to the Shahnameh hero Rostam.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%B1%D8%B3%D8%AA%D9%85',
  },
  {
    nameFa: 'قلعه بمپور',
    nameEn: 'Bampur Castle',
    province: 'Sistan & Baluchestan',
    descFa: 'محوطه باستانی در بمپور با قدمت هزاران ساله.',
    descEn: 'An archaeological site in Bampur dating back thousands of years.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%A8%D9%85%D9%BE%D9%88%D8%B1',
  },
  {
    nameFa: 'قلعه سرباز',
    nameEn: 'Sarbaz Castle',
    province: 'Sistan & Baluchestan',
    descFa: 'دژی تاریخی در شهرستان سرباز بلوچستان.',
    descEn: 'A historic fortress in Sarbaz, Baluchestan.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%B3%D8%B1%D8%A8%D8%A7%D8%B2',
  },
  {
    nameFa: 'قلعه تیس',
    nameEn: 'Tis Castle',
    province: 'Sistan & Baluchestan',
    descFa: 'قلعه ساحلی پرتغالی در نزدیکی چابهار.',
    descEn: 'A Portuguese coastal fortress near Chabahar.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%AA%DB%8C%D8%B3',
  },
  {
    nameFa: 'قلعه سمیران',
    nameEn: 'Samiran Castle',
    province: 'Qazvin',
    descFa: 'دژ اسماعیلی در ارتفاعات الموت قزوین.',
    descEn: 'An Ismaili fortress in the Alamut heights of Qazvin.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%B3%D9%85%DB%8C%D8%B1%D8%A7%D9%86',
  },
  {
    nameFa: 'قلعه شیرکوه',
    nameEn: 'Shirkuh Castle',
    province: 'Qazvin',
    descFa: 'دژ کوهستانی در منطقه الموت قزوین.',
    descEn: 'A mountain fortress in the Alamut region of Qazvin.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%B4%DB%8C%D8%B1%DA%A9%D9%88%D9%87',
  },
  {
    nameFa: 'ارگ کاشمر',
    nameEn: 'Kashmar Citadel',
    province: 'Razavi Khorasan',
    descFa: 'ارگ تاریخی شهر کاشمر در خراسان رضوی.',
    descEn: 'The historic citadel of Kashmar in Razavi Khorasan.',
    wiki: 'https://fa.wikipedia.org/wiki/%D8%A7%D8%B1%DA%AF_%DA%A9%D8%A7%D8%B4%D9%85%D8%B1',
  },
  {
    nameFa: 'قلعه آتشگاه',
    nameEn: 'Atashgah Castle',
    province: 'Razavi Khorasan',
    descFa: 'دژ و آتشکده باستانی در کاشمر.',
    descEn: 'An ancient fortress and fire temple in Kashmar.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%A2%D8%AA%D8%B4%DA%AF%D8%A7%D9%87',
  },
  {
    nameFa: 'قلعه نامق',
    nameEn: 'Namaq Castle',
    province: 'Razavi Khorasan',
    descFa: 'دژ تاریخی در روستای نامق خراسان رضوی.',
    descEn: 'A historic fortress in Namaq village, Razavi Khorasan.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D9%86%D8%A7%D9%85%D9%82',
  },
  {
    nameFa: 'قلعه کندر',
    nameEn: 'Kondar Castle',
    province: 'Razavi Khorasan',
    descFa: 'دژی تاریخی در خراسان رضوی.',
    descEn: 'A historic fortress in Razavi Khorasan province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%DA%A9%D9%86%D8%AF%D8%B1',
  },
  {
    nameFa: 'قلعه بندبن',
    nameEn: 'Bandbon Castle',
    province: 'Gilan',
    descFa: 'دژی جنگلی در گیلان با معماری دفاعی.',
    descEn: 'A forest fortress in Gilan with defensive architecture.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%A8%D9%86%D8%AF%D8%A8%D9%86',
  },
  {
    nameFa: 'قلعه لیسار',
    nameEn: 'Lisar Castle',
    province: 'Gilan',
    descFa: 'قلعه‌ای تاریخی در تالش گیلان.',
    descEn: 'A historic castle in Talesh, Gilan province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D9%84%DB%8C%D8%B3%D8%A7%D8%B1',
  },
  {
    nameFa: 'قلعه اسپهبد خورشید',
    nameEn: 'Espahbod Khorshid Castle',
    province: 'Mazandaran',
    descFa: 'دژ کوهستانی در مازندران منسوب به اسپهبدان طبرستان.',
    descEn: 'A mountain fortress in Mazandaran attributed to the Espahbods of Tabarestan.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%A7%D8%B3%D9%BE%D9%87%D8%A8%D8%AF_%D8%AE%D9%88%D8%B1%D8%B4%DB%8C%D8%AF',
  },
  {
    nameFa: 'قلعه کنگلو',
    nameEn: 'Kangalu Castle',
    province: 'Mazandaran',
    descFa: 'قلعه‌ای تاریخی در مازندران.',
    descEn: 'A historic castle in Mazandaran province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%DA%A9%D9%86%DA%AF%D9%84%D9%88',
  },
  {
    nameFa: 'قلعه جلال‌الدین',
    nameEn: 'Jalal al-Din Castle',
    province: 'North Khorasan',
    descFa: 'دژی تاریخی در خراسان شمالی.',
    descEn: 'A historic fortress in North Khorasan province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%AC%D9%84%D8%A7%D9%84_%D8%A7%D9%84%D8%AF%DB%8C%D9%86',
  },
  {
    nameFa: 'قلعه کرشاهی',
    nameEn: 'Kareshahi Castle',
    province: 'Isfahan',
    descFa: 'دومین بنای خشتی ایران پس از ارگ بم، در ابوزیدآباد اصفهان.',
    descEn: 'Iran\'s second-largest adobe structure after Arg-e Bam, in Abuzeydabad, Isfahan.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%DA%A9%D8%B1%D8%B4%D8%A7%D9%87%DB%8C',
  },
  {
    nameFa: 'قلعه اردشیر',
    nameEn: 'Ardeshir Castle',
    province: 'Kerman',
    descFa: 'دژ ساسانی در فیروزآباد منسوب به اردشیر بابکان.',
    descEn: 'A Sasanian fortress attributed to Ardashir I, founder of the Sasanian dynasty.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%A7%D8%B1%D8%AF%D8%B4%DB%8C%D8%B1',
  },
  {
    nameFa: 'ارگ انار',
    nameEn: 'Arg-e Anar',
    province: 'Kerman',
    descFa: 'ارگ تاریخی در شهرستان انار کرمان.',
    descEn: 'A historic citadel in Anar, Kerman province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D8%A7%D8%B1%DA%AF_%D8%A7%D9%86%D8%A7%D8%B1',
  },
  {
    nameFa: 'قلعه سموران',
    nameEn: 'Samouran Castle',
    province: 'Kerman',
    descFa: 'دژ تاریخی در استان کرمان.',
    descEn: 'A historic fortress in Kerman province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%B3%D9%85%D9%88%D8%B1%D8%A7%D9%86',
  },
  {
    nameFa: 'قلعه زیویه',
    nameEn: 'Ziwiye Castle',
    province: 'Kurdistan',
    descFa: 'محوطه باستانی مشهور در سقز کردستان با یافته‌های طلایی.',
    descEn: 'A famous archaeological site in Saqqez, Kurdistan, known for its golden treasures.',
    wiki: 'https://en.wikipedia.org/wiki/Ziwiye',
  },
  {
    nameFa: 'قلعه حسن‌آباد',
    nameEn: 'Hasanabad Castle',
    province: 'Kurdistan',
    descFa: 'دژ تاریخی در کردستان.',
    descEn: 'A historic fortress in Kurdistan province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%AD%D8%B3%D9%86%E2%80%8C%D8%A2%D8%A8%D8%A7%D8%AF',
  },
  {
    nameFa: 'قلعه تبر',
    nameEn: 'Tabar Castle',
    province: 'Fars',
    descFa: 'دژ تاریخی در فارس معروف به خورشه.',
    descEn: 'A historic fortress in Fars also known as Khursha.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%AA%D8%A8%D8%B1',
  },
  {
    nameFa: 'قلعه اژدهاپیکر',
    nameEn: 'Ezhdeha Peykar Castle',
    province: 'Fars',
    descFa: 'دژ باستانی با نقش اژدها در استان فارس.',
    descEn: 'An ancient fortress with dragon motifs in Fars province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%A7%DA%98%D8%AF%D9%87%D8%A7_%D9%BE%DB%8C%DA%A9%D8%B1',
  },
  {
    nameFa: 'قلعه استخر',
    nameEn: 'Istakhr Castle',
    province: 'Fars',
    descFa: 'دژ و شهر باستانی ساسانی در نزدیکی تخت جمشید.',
    descEn: 'A Sasanian fortress and ancient city near Persepolis.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%A7%D8%B3%D8%AA%D8%AE%D8%B1',
  },
  {
    nameFa: 'قلعه قدمگاه',
    nameEn: 'Ghadamgah Castle',
    province: 'Fars',
    descFa: 'دژ تاریخی در استان فارس.',
    descEn: 'A historic fortress in Fars province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D9%82%D8%AF%D9%85%DA%AF%D8%A7%D9%87',
  },
  {
    nameFa: 'قلعه سفید',
    nameEn: 'Sefid Castle',
    province: 'Fars',
    descFa: 'دژی تاریخی به نام قلعه سفید در فارس.',
    descEn: 'A historic fortress known as the "White Castle" in Fars.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%B3%D9%81%DB%8C%D8%AF',
  },
  {
    nameFa: 'قلعه مهرجرد',
    nameEn: 'Mehrjerd Castle',
    province: 'Yazd',
    descFa: 'دژ تاریخی در شهرستان مهریز یزد.',
    descEn: 'A historic fortress in Mehriz, Yazd province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D9%85%D9%87%D8%B1%D8%AC%D8%B1%D8%AF',
  },
  {
    nameFa: 'قلعه شواز',
    nameEn: 'Shavaz Castle',
    province: 'Yazd',
    descFa: 'دژ تاریخی در استان یزد.',
    descEn: 'A historic fortress in Yazd province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%B4%D9%88%D8%A7%D8%B2',
  },
  {
    nameFa: 'قلعه لشتان',
    nameEn: 'Leshtan Castle',
    province: 'Hormozgan',
    descFa: 'دژ ساحلی در هرمزگان.',
    descEn: 'A coastal fortress in Hormozgan province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D9%84%D8%B4%D8%AA%D8%A7%D9%86',
  },
  {
    nameFa: 'قلعه هرمز',
    nameEn: 'Hormuz Castle',
    province: 'Hormozgan',
    descFa: 'قلعه‌ای تاریخی در جزیره هرمز.',
    descEn: 'A historic castle on Hormuz Island.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D9%87%D8%B1%D9%85%D8%B2',
  },
  {
    nameFa: 'قلعه لافت',
    nameEn: 'Laft Castle',
    province: 'Hormozgan',
    descFa: 'قلعه‌ای در روستای لافت جزیره قشم.',
    descEn: 'A castle in Laft village on Qeshm Island.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D9%84%D8%A7%D9%81%D8%AA',
  },
  {
    nameFa: 'قلعه هزاره',
    nameEn: 'Hazareh Castle',
    province: 'Hormozgan',
    descFa: 'قلعه بی‌بی‌مینو در میناب هرمزگان.',
    descEn: 'Also known as Bibi Minu castle, located in Minab, Hormozgan.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D9%87%D8%B2%D8%A7%D8%B1%D9%87',
  },
  {
    nameFa: 'قلعه چوبین',
    nameEn: 'Choubin Castle',
    province: 'Hamadan',
    descFa: 'دژ تاریخی در همدان.',
    descEn: 'A historic fortress in Hamadan province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%DA%86%D9%88%D8%A8%DB%8C%D9%86',
  },
  {
    nameFa: 'نوشیجان',
    nameEn: 'Nush-e Jan',
    province: 'Hamadan',
    descFa: 'دژ و آتشکده مادی با قدمت ۳۰۰۰ ساله در همدان.',
    descEn: 'A 3,000-year-old Median fortress and fire temple in Hamadan.',
    wiki: 'https://en.wikipedia.org/wiki/Nush-e_Jan',
  },
  {
    nameFa: 'قلعه باجول',
    nameEn: 'Bajol Castle',
    province: 'Lorestan',
    descFa: 'دژ تاریخی در لرستان.',
    descEn: 'A historic fortress in Lorestan province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%A8%D8%A7%D8%AC%D9%88%D9%84',
  },
  {
    nameFa: 'قلعه بهرام',
    nameEn: 'Bahram Castle',
    province: 'Lorestan',
    descFa: 'دژ تاریخی در لرستان منسوب به بهرام.',
    descEn: 'A historic fortress in Lorestan named after Bahram.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%A8%D9%87%D8%B1%D8%A7%D9%85',
  },
  {
    nameFa: 'قلعه نصیر',
    nameEn: 'Nasir Castle',
    province: 'Lorestan',
    descFa: 'دژ تاریخی در لرستان.',
    descEn: 'A historic fortress in Lorestan province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D9%86%D8%B5%DB%8C%D8%B1',
  },
  {
    nameFa: 'قلعه رزه',
    nameEn: 'Razeh Castle',
    province: 'Lorestan',
    descFa: 'بنای تاریخی در لرستان.',
    descEn: 'A historic structure in Lorestan province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%B1%D8%B2%D9%87_(%D8%A8%D9%86%D8%A7)',
  },
  {
    nameFa: 'آق‌قلعه',
    nameEn: 'Aq Qaleh',
    province: 'Golestan',
    descFa: 'دژ سفید تاریخی در گلستان معروف به اسپی‌دژ.',
    descEn: 'A historic "White Castle" in Golestan, also known as Espi Dezh.',
    wiki: 'https://fa.wikipedia.org/wiki/%D8%A2%D9%82_%D9%82%D9%84%D8%B9%D9%87',
  },
  {
    nameFa: 'قلعه جمشیدی',
    nameEn: 'Jamshidi Castle',
    province: 'Markazi',
    descFa: 'قلعه‌ای تاریخی در استان مرکزی.',
    descEn: 'A historic castle in Markazi province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%AC%D9%85%D8%B4%DB%8C%D8%AF%DB%8C',
  },
  {
    nameFa: 'قلعه حاج وکیل',
    nameEn: 'Haj Vakil Castle',
    province: 'Markazi',
    descFa: 'قلعه قاجاری در استان مرکزی.',
    descEn: 'A Qajar-era castle in Markazi province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%AD%D8%A7%D8%AC_%D9%88%DA%A9%DB%8C%D9%84',
  },
  {
    nameFa: 'قلعه خاندان بهادری',
    nameEn: 'Bahador Clan Castle',
    province: 'Markazi',
    descFa: 'دژ تاریخی متعلق به خاندان بهادری در استان مرکزی.',
    descEn: 'A historic fortress of the Bahador clan in Markazi province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%AE%D8%A7%D9%86%D8%AF%D8%A7%D9%86_%D8%A8%D9%87%D8%A7%D8%AF%D8%B1%DB%8C',
  },
  {
    nameFa: 'قلعه قرمز',
    nameEn: 'Ghermez Castle',
    province: 'Qom',
    descFa: 'قلعه سرخ‌رنگ تاریخی در استان قم.',
    descEn: 'A historic "Red Castle" in Qom province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D9%82%D8%B1%D9%85%D8%B2',
  },
  {
    nameFa: 'قلعه مظفرآباد',
    nameEn: 'Mozaffarabad Castle',
    province: 'Qom',
    descFa: 'دژ تاریخی در استان قم.',
    descEn: 'A historic fortress in Qom province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D9%85%D8%B8%D9%81%D8%B1%D8%A2%D8%A8%D8%A7%D8%AF',
  },
  {
    nameFa: 'قلعه پهلوان بادی',
    nameEn: 'Pahlavan Badi Castle',
    province: 'Yazd',
    descFa: 'دژ تاریخی در استان یزد.',
    descEn: 'A historic fortress in Yazd province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D9%BE%D9%87%D9%84%D9%88%D8%A7%D9%86_%D8%A8%D8%A7%D8%AF%DB%8C',
  },
  {
    nameFa: 'قلعه ربات',
    nameEn: 'Robat Castle',
    province: 'Yazd',
    descFa: 'دژ و کاروانسرای تاریخی در استان یزد.',
    descEn: 'A historic fortress and caravanserai in Yazd province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%B1%D8%A8%D8%A7%D8%B7',
  },
  {
    nameFa: 'قلعه بزه‌رود',
    nameEn: 'Bazeh Rud Castle',
    province: 'Kermanshah',
    descFa: 'دژ تاریخی در کرمانشاه.',
    descEn: 'A historic fortress in Kermanshah province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%A8%D8%B2%D9%87_%D8%B1%D9%88%D8%AF',
  },
  {
    nameFa: 'قلعه یزدگرد',
    nameEn: 'Yazdgerd Castle',
    province: 'Kermanshah',
    descFa: 'دژ ساسانی در کرمانشاه منسوب به یزدگرد.',
    descEn: 'A Sasanian fortress in Kermanshah attributed to Yazdgerd.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%DB%8C%D8%B2%D8%AF%DA%AF%D8%B1%D8%AF_(%D8%B2%D8%B1%D8%AF%D9%87)',
  },
  {
    nameFa: 'قلعه شامبرکان',
    nameEn: 'Shamborkan Castle',
    province: 'Kohgiluyeh & Boyer-Ahmad',
    descFa: 'دژ تاریخی در کهگیلویه و بویراحمد.',
    descEn: 'A historic fortress in Kohgiluyeh & Boyer-Ahmad province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%B4%D8%A7%D9%85%D8%A8%D8%B1%DA%A9%D8%A7%D9%86',
  },
  {
    nameFa: 'قلعه خورموج',
    nameEn: 'Khormooj Castle',
    province: 'Bushehr',
    descFa: 'دژ تاریخی در بوشهر.',
    descEn: 'A historic fortress in Bushehr province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%AE%D9%88%D8%B1%D9%85%D9%88%D8%AC',
  },
  {
    nameFa: 'قلعه ارجان',
    nameEn: 'Arjan Castle',
    province: 'Khuzestan',
    descFa: 'دژ باستانی در بهبهان خوزستان.',
    descEn: 'An ancient fortress in Behbahan, Khuzestan.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%A7%D8%B1%D8%AC%D8%A7%D9%86',
  },
  {
    nameFa: 'رباط شرف',
    nameEn: 'Robat-e Sharaf',
    province: 'Razavi Khorasan',
    descFa: 'کاروانسرا و دژ سلجوقی در خراسان رضوی با تزئینات آجری منحصربه‌فرد.',
    descEn: 'A Seljuk caravanserai and fortress in Khorasan with unique brickwork decorations.',
    wiki: 'https://en.wikipedia.org/wiki/Robat-e_Sharaf',
  },
  {
    nameFa: 'قلعه نهبندان',
    nameEn: 'Nehbandan Castle',
    province: 'South Khorasan',
    descFa: 'دژ تاریخی در شهرستان نهبندان.',
    descEn: 'A historic fortress in Nehbandan.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D9%86%D9%87%D8%A8%D9%86%D8%AF%D8%A7%D9%86',
  },
  {
    nameFa: 'ارگ کلاه‌فرنگی',
    nameEn: 'Kolah Farangi Citadel',
    province: 'South Khorasan',
    descFa: 'ارگ تاریخی در خراسان جنوبی.',
    descEn: 'A historic citadel in South Khorasan.',
    wiki: 'https://fa.wikipedia.org/wiki/%D8%A7%D8%B1%DA%AF_%DA%A9%D9%84%D8%A7%D9%87_%D9%81%D8%B1%D9%86%DA%AF%DB%8C',
  },
  {
    nameFa: 'قلعه کشیت',
    nameEn: 'Keshit Castle',
    province: 'Kerman',
    descFa: 'دژ تاریخی در شهرستان کرمان.',
    descEn: 'A historic fortress in Kerman.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%DA%A9%D8%B4%DB%8C%D8%AA',
  },
  {
    nameFa: 'قلعه گلباف',
    nameEn: 'Golbaf Castle',
    province: 'Kerman',
    descFa: 'دژ تاریخی در گلباف کرمان.',
    descEn: 'A historic fortress in Golbaf, Kerman.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%DA%AF%D9%84%D8%A8%D8%A7%D9%81',
  },
  {
    nameFa: 'قلعه جونقان',
    nameEn: 'Junaqan Castle',
    province: 'Chaharmahal & Bakhtiari',
    descFa: 'دژ تاریخی در چهارمحال و بختیاری.',
    descEn: 'A historic fortress in Chaharmahal & Bakhtiari.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%AC%D9%88%D9%86%D9%82%D8%A7%D9%86',
  },
  {
    nameFa: 'قلعه چهل‌دختران',
    nameEn: 'Forty Maidens Castle',
    province: 'Sistan & Baluchestan',
    descFa: 'دژ باستانی در سیستان با افسانه چهل دختر.',
    descEn: 'An ancient fortress in Sistan with the legend of forty maidens.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%DA%86%D9%87%D9%84_%D8%AF%D8%AE%D8%AA%D8%B1%D8%A7%D9%86',
  },
  {
    nameFa: 'قلعه تیمور',
    nameEn: 'Timur Castle',
    province: 'Sistan & Baluchestan',
    descFa: 'دژی منسوب به تیمور لنگ در سیستان.',
    descEn: 'A fortress attributed to Timur (Tamerlane) in Sistan.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%AA%DB%8C%D9%85%D9%88%D8%B1',
  },
  {
    nameFa: 'قلعه ساسان',
    nameEn: 'Sasan Castle',
    province: 'Qazvin',
    descFa: 'دژ باستانی معروف به آرامگاه بزرگ در قزوین.',
    descEn: 'An ancient fortress known as the "Great Tomb" in Qazvin.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%B3%D8%A7%D8%B3%D8%A7%D9%86',
  },
  {
    nameFa: 'قلعه خمیر',
    nameEn: 'Khamir Castle',
    province: 'Hormozgan',
    descFa: 'دژ تاریخی در بندر خمیر هرمزگان.',
    descEn: 'A historic fortress in Bandar Khamir, Hormozgan.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%AE%D9%85%DB%8C%D8%B1',
  },
  {
    nameFa: 'دژ شیخ‌مکان',
    nameEn: 'Sheikh Makan Fortress',
    province: 'Ilam',
    descFa: 'دژ تاریخی در ایلام.',
    descEn: 'A historic fortress in Ilam province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D8%AF%DA%98_%D8%B4%DB%8C%D8%AE_%D9%85%DA%A9%D8%A7%D9%86',
  },
  {
    nameFa: 'قلعه گوریا',
    nameEn: 'Guria Castle',
    province: 'Ilam',
    descFa: 'دژ تاریخی در ایلام.',
    descEn: 'A historic fortress in Ilam province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%DA%AF%D9%88%D8%B1%DB%8C%D8%A7',
  },
  {
    nameFa: 'قلعه کردشت',
    nameEn: 'Kordshit Castle',
    province: 'East Azerbaijan',
    descFa: 'دژ تاریخی در جلفای آذربایجان شرقی.',
    descEn: 'A historic fortress in Jolfa, East Azerbaijan.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%DA%A9%D8%B1%D8%AF%D8%B4%D8%AA',
  },
  {
    nameFa: 'قلعه سیاه',
    nameEn: 'Black Castle',
    province: 'West Azerbaijan',
    descFa: 'دژ تاریخی معروف به قلعه سیاه در آذربایجان غربی.',
    descEn: 'A historic fortress known as the "Black Castle" in West Azerbaijan.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%B3%DB%8C%D8%A7%D9%87',
  },
  {
    nameFa: 'قلعه مروست',
    nameEn: 'Morvast Castle',
    province: 'Yazd',
    descFa: 'دژ تاریخی در شهرستان خاتم یزد.',
    descEn: 'A historic fortress in Khatam, Yazd province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D9%85%D8%B1%D9%88%D8%B3%D8%AA',
  },
  {
    nameFa: 'قلعه ابرندآباد',
    nameEn: 'Abrandabad Castle',
    province: 'Yazd',
    descFa: 'دژ تاریخی در استان یزد.',
    descEn: 'A historic fortress in Yazd province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%A7%D8%A8%D8%B1%D9%86%D8%AF%D8%A2%D8%A8%D8%A7%D8%AF',
  },
  {
    nameFa: 'قلعه رحمت‌آباد',
    nameEn: 'Rahmatabad Castle',
    province: 'Yazd',
    descFa: 'دژ تاریخی در استان یزد.',
    descEn: 'A historic fortress in Yazd province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%B1%D8%AD%D9%85%D8%AA_%D8%A2%D8%A8%D8%A7%D8%AF',
  },
  {
    nameFa: 'قلعه دیو',
    nameEn: 'Div Castle',
    province: 'Isfahan',
    descFa: 'دژ تاریخی معروف به قلعه دیو در اصفهان.',
    descEn: 'A historic fortress known as the "Demon Castle" in Isfahan.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%AF%DB%8C%D9%88',
  },
  {
    nameFa: 'قلعه نقاره‌خانه',
    nameEn: 'Naghareh Khaneh Castle',
    province: 'Tehran',
    descFa: 'دژ تاریخی در ری تهران.',
    descEn: 'A historic fortress in Rey, Tehran.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D9%86%D9%82%D8%A7%D8%B1%D9%87_%D8%AE%D8%A7%D9%86%D9%87',
  },
  {
    nameFa: 'قلعه بردستان',
    nameEn: 'Bardestan Castle',
    province: 'Bushehr',
    descFa: 'دژ تاریخی در بوشهر.',
    descEn: 'A historic fortress in Bushehr province.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%D8%A8%D8%B1%D8%AF%D8%B3%D8%AA%D8%A7%D9%86',
  },
  {
    nameFa: 'قلعه منیژه',
    nameEn: 'Manizheh Castle',
    province: 'Lorestan',
    descFa: 'دژ تاریخی در لرستان با نامی اسطوره‌ای.',
    descEn: 'A historic fortress in Lorestan with a mythical name.',
    wiki: LIST_PAGE,
  },
  {
    nameFa: 'قلعه کوه قائن',
    nameEn: 'Qaen Mountain Castle',
    province: 'South Khorasan',
    descFa: 'دژ کوهستانی باستانی در قائن معروف به آرتاگوانا.',
    descEn: 'An ancient mountain fortress in Qaen, also known as Artagoana.',
    wiki: 'https://fa.wikipedia.org/wiki/%D9%82%D9%84%D8%B9%D9%87_%DA%A9%D9%88%D9%87_%D9%82%D8%A7%D8%A6%D9%86',
  },
];

/**
 * Detect whether a text string is predominantly Persian/Arabic script.
 * Uses Unicode character ranges for Arabic script (which includes Persian).
 */
export function isPersian(text: string): boolean {
  // Persian/Arabic unicode ranges
  const persianChars = text.match(/[\u0600-\u06FF\u0750-\u077F\uFB50-\uFDFF\uFE70-\uFEFF]/g);
  const latinChars = text.match(/[a-zA-Z]/g);
  const pCount = persianChars?.length ?? 0;
  const lCount = latinChars?.length ?? 0;
  if (pCount === 0 && lCount === 0) return false;
  return pCount > lCount;
}

/**
 * Pick a random castle index, avoiding indices already in use by other chats.
 */
export function pickCastleIndex(usedIndices: Set<number>): number {
  const total = IRAN_CASTLES.length;
  if (usedIndices.size >= total) {
    // All castles used — just pick a random one
    return Math.floor(Math.random() * total);
  }
  let idx: number;
  do {
    idx = Math.floor(Math.random() * total);
  } while (usedIndices.has(idx));
  return idx;
}
