// coverTextsWorld.ts
// World poetry cover texts for steganography (separate from Persian coverTexts.ts)
// Languages: English, Arabic, French, German, Spanish, Russian, Italian
// All texts are from public-domain authors.

export type WorldCoverCategory =
  | 'english'
  | 'arabic'
  | 'french'
  | 'german'
  | 'spanish'
  | 'russian'
  | 'italian';

interface WorldCoverCategoryMeta {
  label: string;
  labelEn: string;
  count: number;
}

export const WORLD_COVER_CATEGORY_META: Record<WorldCoverCategory, WorldCoverCategoryMeta> = {
  english: { label: 'English Poetry', labelEn: 'English', count: 600 },
  arabic:  { label: 'شعر عربی',        labelEn: 'Arabic',  count: 70 },
  french:  { label: 'Poésie française', labelEn: 'French', count: 90 },
  german:  { label: 'Deutsche Dichtung', labelEn: 'German', count: 90 },
  spanish: { label: 'Poesía española',  labelEn: 'Spanish', count: 50 },
  russian: { label: 'Русская поэзия',   labelEn: 'Russian', count: 50 },
  italian: { label: 'Poesia italiana',  labelEn: 'Italian', count: 50 },
};

export const WORLD_COVER_CATEGORIES: WorldCoverCategory[] = [
  'english', 'arabic', 'french', 'german', 'spanish', 'russian', 'italian',
];

const WORLD_COVER_TEXTS: Record<WorldCoverCategory, string[]> = {
  english: [
  "Not from the stars do I my judgement pluck; / And yet methinks I have astronomy,",
  "Lascivious grace, in whom all ill well shows, / Kill me with spites yet we must not be foes.",
  "Towards this afflicted fancy fastly drew, / And, privileged by age, desires to know",
  "Look! what thy memory cannot contain, / Commit to these waste blanks, and thou shalt find",
  "'That horse his mettle from his rider takes: / Proud of subjection, noble by the sway,",
  "And I, a tyrant, have no leisure taken / To weigh how once I suffer'd in your crime.",
  "Is it thy will, thy image should keep open / My heavy eyelids to the weary night?",
  "Nor that full star that ushers in the even, / Doth half that glory to the sober west,",
  "Seeking that beauteous roof to ruinate / Which to repair should be thy chief desire.",
  "Each cheek a river running from a fount / With brinish current downward flow'd apace:",
  "'gainst shame, / And sweetens, in the suffering pangs it bears,",
  "So that eternal love in love's fresh case, / Weighs not the dust and injury of age,",
  "Be thou the tenth Muse, ten times more in worth / Than those old nine which rhymers invocate;",
  "Thy youth's proud livery so gazed on now, / Will be a tatter'd weed of small worth held:",
  "O! call not me to justify the wrong / That thy unkindness lays upon my heart;",
  "But if the while I think on thee, dear friend, / All losses are restor'd and sorrows end.",
  "Receiving nought by elements so slow / But heavy tears, badges of either's woe.",
  "And life no longer than thy love will stay, / For it depends upon that love of thine.",
  "And art made tongue-tied by authority, / And folly--doctor-like--controlling skill,",
  "Of young, of old; and sexes both enchanted, / To dwell with him in thoughts, or to remain",
  "Or some fierce thing replete with too much rage, / Whose strength's abundance weakens his own heart;",
  "Nor gives to necessary wrinkles place, / But makes antiquity for aye his page;",
  "I see a better state to me belongs / Than that which on thy humour doth depend:",
  "Mine own self-love quite contrary I read; / Self so self-loving were iniquity.",
  "Or who is he so fond will be the tomb, / Of his self-love to stop posterity?",
  "Lean penury within that pen doth dwell / That to his subject lends not some small glory;",
  "Since all alike my songs and praises be / To one, of one, still such, and ever so.",
  "To mourn for me since mourning doth thee grace, / And suit thy pity like in every part.",
  "Growing a bath and healthful remedy, / For men diseas'd; but I, my mistress' thrall,",
  "If eyes, corrupt by over-partial looks, / Be anchor'd in the bay where all men ride,",
  "Upon thy side, against myself I'll fight, / And prove thee virtuous, though thou art forsworn.",
  "Came there for cure and this by that I prove, / Love's fire heats water, water cools not love.",
  "Cuckoo, cuckoo!--O word of fear, / Unpleasing to a married ear!",
  "Thee have I not lock'd up in any chest, / Save where thou art not, though I feel thou art,",
  "Desiring this man's art, and that man's scope, / With what I most enjoy contented least;",
  "Doth homage to his new-appearing sight, / Serving with looks his sacred majesty;",
  "On newer proof, to try an older friend, / A god in love, to whom I am confin'd.",
  "Then heigh-ho, the holly! / This life is most jolly.",
  "For never-resting time leads summer on / To hideous winter, and confounds him there;",
  "So flatter I the swart-complexion'd night, / When sparkling stars twire not thou gild'st the even.",
  "The thing we have not, mastering what not strives, / Playing the place which did no form receive,",
  "Ten times thy self were happier than thou art, / If ten of thine ten times refigur'd thee:",
  "Or laid great bases for eternity, / Which proves more short than waste or ruining?",
  "Which alters when it alteration finds, / Or bends with the remover to remove:",
  "Mine eye and heart are at a mortal war, / How to divide the conquest of thy sight;",
  "Believed her eyes when they to assail begun, / All vows and consecrations giving place:",
  "Be it lawful I love thee, as thou lov'st those / Whom thine eyes woo as mine importune thee:",
  "No enemy / But winter and rough weather.",
  "Until life's composition be recur'd / By those swift messengers return'd from thee,",
  "Is't not enough to torture me alone, / But slave to slavery my sweet'st friend must be?",
  "When thou reviewest this, thou dost review / The very part was consecrate to thee:",
  "Where art thou Muse that thou forget'st so long, / To speak of that which gives thee all thy might?",
  "Alas! 'tis true, I have gone here and there, / And made my self a motley to the view,",
  "Of paled pearls and rubies red as blood; / Figuring that they their passions likewise lent me",
  "And shalt by fortune once more re-survey / These poor rude lines of thy deceased lover,",
  "So thou, thyself outgoing in thy noon: / Unlook'd, on diest unless thou get a son.",
  "Or swooning paleness; and he takes and leaves, / In either's aptness, as it best deceives,",
  "And yet, love knows it is a greater grief / To bear love's wrong, than hate's known injury.",
  "How would, I say, mine eyes be blessed made / By looking on thee in the living day,",
  "And trouble deaf heaven with my bootless cries, / And look upon myself, and curse my fate,",
  "The first my thought, the other my desire, / These present-absent with swift motion slide.",
  "Thy outward thus with outward praise is crown'd; / But those same tongues, that give thee so thine own,",
  "Therefore my mistress' eyes are raven black, / Her eyes so suited, and they mourners seem",
  "When I have seen by Time's fell hand defac'd / The rich-proud cost of outworn buried age;",
  "Make thee another self for love of me, / That beauty still may live in thine or thee.",
  "To blush at speeches rank to weep at woes, / Or to turn white and swoon at tragic shows.",
  "Those children nursed, deliver'd from thy brain, / To take a new acquaintance of thy mind.",
  "Farewell! thou art too dear for my possessing, / And like enough thou know'st thy estimate,",
  "Thine eyes, that taught the dumb on high to sing / And heavy ignorance aloft to fly,",
  "To me that languish'd for her sake: / But when she saw my woeful state,",
  "The aloes of all forces, shocks, and fears. / ''Now all these hearts that do on mine depend,",
  "The destined ill she must herself assay? / Or forced examples, 'gainst her own content,",
  "Whereto his invised properties did tend; / The deep-green emerald, in whose fresh regard",
  "And the just pleasure lost, which is so deem'd / Not by our feeling, but by others' seeing:",
  "If any, be a satire to decay, / And make time's spoils despised every where.",
  "If Nature, sovereign mistress over wrack, / As thou goest onwards, still will pluck thee back,",
  "The scars of battle 'scapeth by the flight, / And makes her absence valiant, not her might.",
  "Enjoy'd no sooner but despised straight; / Past reason hunted; and no sooner had,",
  "And comely-distant sits he by her side; / When he again desires her, being sat,",
  "Look! what an unthrift in the world doth spend / Shifts but his place, for still the world enjoys it;",
  "I have seen roses damask'd, red and white, / But no such roses see I in her cheeks;",
  "But beauty's waste hath in the world an end, / And kept unused the user so destroys it.",
  "Who heaven itself for ornament doth use / And every fair with his fair doth rehearse,",
  "Thou that art now the world's fresh ornament, / And only herald to the gaudy spring,",
  "For I have sworn thee fair; more perjur'd I, / To swear against the truth so foul a lie!",
  "But that wild music burthens every bough, / And sweets grown common lose their dear delight.",
  "And controversy hence a question takes, / Whether the horse by him became his deed,",
  "So shall I live, supposing thou art true, / Like a deceived husband; so love's face",
  "If thou wilt leave me, do not leave me last, / When other petty griefs have done their spite,",
  "For since each hand hath put on Nature's power, / Fairing the foul with Art's false borrowed face,",
  "And right perfection wrongfully disgrac'd, / And strength by limping sway disabled",
  "Yet this abundant issue seem'd to me / But hope of orphans, and unfather'd fruit;",
  "O! love's best habit is in seeming trust, / And age in love, loves not to have years told:",
  "He learn'd but surety-like to write for me, / Under that bond that him as fast doth bind.",
  "And rather make them born to our desire / Than think that we before have heard them told.",
  "O benefit of ill! now I find true / That better is, by evil still made better;",
  "Since I left you, mine eye is in my mind; / And that which governs me to go about",
  "Therefore to give them from me was I bold, / To trust those tables that receive thee more:",
  "To leave the battery that you make 'gainst mine, / Lending soft audience to my sweet design,",
  "So shall thou feed on Death, that feeds on men, / And Death once dead, there's no more dying then.",
  "But these particulars are not my measure, / All these I better in one general best.",
  "O cunning Love! with tears thou keep'st me blind, / Lest eyes well-seeing thy foul faults should find.",
  "So, either by thy picture or my love, / Thy self away, art present still with me;",
  "Under the greenwood tree / Who loves to lie with me,",
  "As subject to Time's love or to Time's hate, / Weeds among weeds, or flowers with flowers gather'd.",
  "O! how I faint when I of you do write, / Knowing a better spirit doth use your name,",
  "They know what beauty is, see where it lies, / Yet what the best is take the worst to be.",
  "Each changing place with that which goes before, / In sequent toil all forwards do contend.",
  "Sap checked with frost, and lusty leaves quite gone, / Beauty o'er-snowed and bareness every where:",
  "'Tis better to be vile than vile esteem'd, / When not to be receives reproach of being;",
  "Poor soul, the centre of my sinful earth, / My sinful earth these rebel powers array,",
  "And therefore art enforced to seek anew / Some fresher stamp of the time-bettering days.",
  "Love's not Time's fool, though rosy lips and cheeks / Within his bending sickle's compass come;",
  "How oft when thou, my music, music play'st, / Upon that blessed wood whose motion sounds",
  "As benefits forgot: / Though thou the waters warp,",
  "They that have power to hurt, and will do none, / That do not do the thing they most do show,",
  "Who, moving others, are themselves as stone, / Unmoved, cold, and to temptation slow;",
  "Who all their parts of me to thee did give, / That due of many now is thine alone:",
  "That she might think me some untutor'd youth, / Unlearned in the world's false subtleties.",
  "Such seems your beauty still. Three winters cold, / Have from the forests shook three summers' pride,",
  "With silvery oak apples, and fir cones brown-- / By all the echoes that about thee ring,",
  "Shall I say 'Crouch!'---Ye groan. What can I then? / O Heaven wide! O unseen parent dear!",
  "When 'mid acclaim, and feasts, and garlands gay, / He stept upon his shepherd throne: the look",
  "In nectar'd clouds and curls through water fair, / So from the arbour roof down swell'd an air",
  "Golden, or rainbow-sided, or purplish, / Vermilion-tail'd, or finn'd with silvery gauze;",
  "Where falling stars dart their artillery forth, / And eagles struggle with the buffeting north",
  "\"I touch'd no lute, I sang not, trod no measures: / I was a lonely youth on desert shores.",
  "By reason of his fallen divinity / Spreading a shade: the Naiad 'mid her reeds",
  "I bow'd a tranced vassal: nor would thence / Have mov'd, even though Amphion's harp had woo'd",
  "And, from the turf, a lullaby doth pass / In every place where infant Orpheus slept.",
  "Ponderest high and deep; and in thy face / I see, astonied, that severe content",
  "About each youthful heart,—with stifled cries, / And rubbing of white hands, and sparkling eyes:",
  "At which we start and fret; till in the end, / Melting into its radiance, we blend,",
  "Alive with sparkles--never, I aver, / Since Ariadne was a vintager,",
  "We are such forest-trees, and our fair boughs / Have bred forth, not pale solitary doves,",
  "A huntress free in\"--At this, sudden fell / Those two sad streams adown a fearful dell.",
  "O think how sweet to me the freshening sluice! / Dost thou now please thy thirst with berry-juice?",
  "The creeper, mellowing for an autumn blush; / And virgin's bower, trailing airily;",
  "'Whence came ye, merry Damsels! whence came ye, / So many, and so many, and such glee?",
  "Presumptuous against love, against the sky, / Against all elements, against the tie",
  "Endymion look'd at her, and press'd her hand, / And said, \"Art thou so pale, who wast so bland",
  "To meet oblivion.\"--As her heart would burst / The maiden sobb'd awhile, and then replied:",
  "The endless sleep of this new-born Adon', / This stranger ay I pitied. For upon",
  "\"How cam'st thou over the unfooted sea? / Or hath that antique mien and robed form",
  "But for her comforting! unhappy sight, / But meeting her blue orbs! Who, who can write",
  "Like to a moving vintage down they came, / Crown'd with green leaves, and faces all on flame;",
  "Stood silent round the shrine: each look was chang'd / To sudden veneration: women meek",
  "His snorting four. Now when his chariot last / Its beams against the zodiac-lion cast,",
  "A crescent he had carv'd, and round it spent / His skill in little stars. The teeming tree",
  "Hour after hour, to each lush-leav'd rill. / Now he is sitting by a shady spring,",
  "Yea, or my veined pebble-floor, that draws / A virgin light to the deep; my grotto-sands",
  "An unknown--but no more: we humbly screen / With uplift hands our foreheads, lowly bending,",
  "And apples, wan with sweetness, gather thee,-- / Cresses that grow where no man may them see,",
  "Pour'd into shapes of curtain'd canopies, / Spangled, and rich with liquid broideries",
  "When yet a child, I heard that kisses drew / Favour from thee, and so I kisses gave",
  "Then it is free to him; and from an urn, / Still fed by melting ice, he takes a draught--",
  "Still brooding o'er the cadence of his lyre; / And thus: \"I need not any hearing tire",
  "O Sorrow! / Why dost borrow",
  "No bigger than an unobserved star, / Or tiny point of fairy scymetar;",
  "What ails thee?\" He could bear no more, and so / Bent his soul fiercely like a spiritual bow,",
  "Brimming the water-lily cups with tears / Cold as my fears.",
  "Sharpening, by degrees, his appetite / To dive into the deepest. Dark, nor light,",
  "Aye on the shores of darkness there is light, / And precipices show untrodden green,",
  "BOOK I / Deep in the shady sadness of a vale",
  "Upon a weeded rock this old man sat, / And his white hair was awful, and a mat",
  "And that fair kneeling Goddess; and then spake, / As with a palsied tongue, and while his beard",
  "Thermopylæ its heroes--not yet dead, / But in old marbles ever beautiful.",
  "Fell sleek about him in a thousand folds-- / Not hiding up an Apollonian curve",
  "I, Coelus, wonder, how they came and whence; / And at the fruits thereof what shapes they be,",
  "And the most patient brilliance of the moon! / And stars by thousands!  Point me out the way",
  "Towards her, and awakes--and, strange, o'erhead, / Of those same fragrant exhalations bred,",
  "And 'tis right just, for well Apollo knows / 'Twould make the Poet quarrel with the rose.",
  "I've been a ranger / In search of pleasure throughout every clime;",
  "There came enchantment with the shifting wind, / That did both drown and keep alive my ears.",
  "All the bright riches of my crystal coffer / To Amphitrite; all my clear-eyed fish,",
  "Before the first of Druids was a child;-- / Long didst thou sit amid our regions wild",
  "And, save when Bacchus kept his ivy tent, / Onward the tiger and the leopard pants,",
  "Tawny and gold, ooz'd slowly from far lands / By my diligent springs; my level lilies, shells,",
  "Dying to embers from their native fire! / There curl'd a purple mist around them; soon,",
  "Among immortals when a God gives sign, / With hushing finger, how he means to load",
  "If this belief from heaven be sent, / If such be Nature's holy plan,",
  "When all at once I saw a crowd, / A host, of golden daffodils;",
  "I heard a thousand blended notes, / While in a grove I sate reclined,",
  "And 'tis my faith that every flower / Enjoys the air it breathes.",
  "A poet could not be but gay, / In such a jocund company!",
  "They flash upon that inward eye / Which is the bliss of solitude;",
  "Beside the lake, beneath the trees, / Fluttering and dancing in the breeze.",
  "Through primrose tufts, in that green bower, / The periwinkle trailed its wreaths;",
  "To her fair works did Nature link / The human soul that through me ran;",
  "For oft, when on my couch I lie / In vacant or in pensive mood,",
  "And I must think, do all I can, / That there was pleasure there.",
  "I wandered lonely as a cloud / That floats on high o'er vales and hills,",
  "Have I not reason to lament / What man has made of man?",
  "The birds around me hopped and played, / Their thoughts I cannot measure:--",
  "The budding twigs spread out their fan, / To catch the breezy air;",
  "I gazed—and gazed—but little thought / What wealth the show to me had brought:",
  "They stretched in never-ending line / Along the margin of a bay:",
  "Continuous as the stars that shine / And twinkle on the milky way,",
  "And then my heart with pleasure fills, / And dances with the daffodils.",
  "But the least motion which they made / It seemed a thrill of pleasure.",
  "In that sweet mood when pleasant thoughts / Bring sad thoughts to the mind.",
  "The waves beside them danced, but they / Out-did the sparkling leaves in glee;",
  "And much it grieved my heart to think / What man has made of man.",
  "Ten thousand saw I at a glance, / Tossing their heads in sprightly dance.",
  "Never had a Doubt -- / Laughs -- at a Scruple --",
  "Her Green People recollect it / When they do not die --",
  "Eve -- and the Anguish -- Grandame's story -- / But -- I was telling a tune -- I heard --",
  "The butterfly obtains / But little sympathy",
  "To balk thee of thy sacred Prey -- / Advancing to thy Den --",
  "Subtle the Sum / That purchase you --",
  "Forbidden fruit a flavor has / That lawful orchards mocks;",
  "The sacred stealth of Boy and Girl / Rebuke it if we can",
  "You see I cannot see -- your lifetime -- / I must guess --",
  "In a Metropolis of Homes / Is easy, possibly --",
  "The Stars are old, that stood for me -- / The West a little worn --",
  "I told myself, \"Take Courage, Friend -- / That -- was a former time --",
  "Remorse is cureless -- the Disease / Not even God -- can heal --",
  "That vanquished her -- defeated Feat -- / Was Fervor's sudden Crown --",
  "My Soul's entire income -- / In ceaseless -- salary --",
  "From Amherst to Cashmere! / I would not stop for night, or storm --",
  "They shall survive -- / There is a sun --",
  "Yet Birds examine it and flee -- / And Vans without a name",
  "Oh Future! thou secreted peace / Or subterranean woe --",
  "It spurn the Grave -- / I told him Worlds I knew",
  "We thirst at first -- 'tis Nature's Act -- / And later -- when we die --",
  "Can tell the definition / So clear of Victory",
  "Gone -- Mr. Bryant's \"Golden Rod\" -- / And Mr. Thomson's \"sheaves.\"",
  "Unto the Saint's slow diligence -- / The Sky --",
  "How He stretched His Anguish to us / That -- is covered too --",
  "The smallest Housewife in the grass, / Yet take her from the Lawn",
  "But they could gag the Tick -- / And Mice won't bark --",
  "Find quaint employ -- / Some with new -- stately feet --",
  "If Immortality unveil / A third event to me",
  "So looking on -- the night -- the morn / Conclude the wonder gay --",
  "The Rapture of a finished Day -- / Returning to the West --",
  "He told a homely tale / And spotted it with tears --",
  "The Crocus -- til she rises / The Vassal of the snow --",
  "In any Forest stirred / But with itself did cold engage",
  "A Trouble lest they're homesick -- / Those Farmers -- and their Wives --",
  "Old fashioned eyes -- / Not easy to surprise!",
  "If only to enclose the Saints / To Affidavit given.",
  "No Autumn's intercepting Chill / Appalls this Tropic Breast --",
  "The very Pattern of the Cheek -- / It varies -- in the Chin --",
  "The Bobolinks around the throne / And Dandelions gold.",
  "She slept beneath a tree -- / Remembered but by me.",
  "He -- must have achieved in person / Equal Paradise --",
  "People -- like the Moth -- / Of Mechlin -- frames --",
  "Because it's Sunday -- all the time -- / And Recess -- never comes --",
  "But acclimated -- pines no more / For that Peninsula --",
  "That little Yellow boys and girls / Were climbing all the while --",
  "With only Birds to interrupt / The Ripple of our Theme --",
  "Relate -- when Neighbors die -- / At what o'clock to heaven -- they fled --",
  "Earring -- or Stone -- / A Watch -- Some Ancient Brooch",
  "How the Waters closed above Him / We shall never know --",
  "Seven summers old / Lovely Lyca told.",
  "\"And because I am happy and dance and sing, / They think they have done me no injury,",
  "That walked among the ancient tree; / Calling the lapsed soul,",
  "\"Love seeketh only Self to please, / To bind another to its delight,",
  "\"Nought loves another as itself, / Nor venerates another so,",
  "She had wandered long, / Hearing wild birds' song.",
  "By sorrow and care's dismay,-- / How shall the summer arise in joy,",
  "Then am I / A happy fly,",
  "When the voices of children are heard on the green, / And laughing is heard on the hill,",
  "Wept for me, for thee, for all, / When He was an infant small.",
  "And the maiden soon forgot her fear. / Tired with kisses sweet,",
  "The virgins of youth and morning bear? / \"Does spring hide its joy,",
  "O rose, thou art sick! / The invisible worm,",
  "\"Well, well, go and play till the light fades away, / And then go home to bed.\"",
  "And I am very small and love to dwell in lowly vales: / So weak the gilded butterfly scarce perches on my head",
  "And Love, the human form divine; / And Peace, the human dress.",
  "Where the holy light / Had just removed the curtains of the night.",
  "\"Love seeketh not itself to please, / Nor for itself hath any care,",
  "In the morning, glad, I see / My foe outstretched beneath the tree.",
  "Did he smile his work to see? / Did he who made the lamb make thee?",
  "Then they followed / Where the vision led,",
  "I'll shade him from the heat till he can bear / To lean in joy upon our Father's knee;",
  "And the Angel told Tom, if he'd be a good boy, / He'd have God for his father, and never want joy.",
  "He is watching while they are in peace, / For they know when their Shepherd is nigh.",
  "Lark in sky,-- / Merrily,",
  "I a child, and thou a lamb, / We are called by His name.",
  "She saw the couches of the dead, & where the fibrous roots / Of every heart on earth infixes deep its restless twists:",
  "I vanish from my pearly throne, and who shall find my place. / Queen of the vales the Lily answered, ask the tender cloud,",
  "The death of Jesus set me free: / Then what have I to do with thee?",
  "Over valleys deep, / While the deserts weep.",
  "And the just man rages in the wilds / Where lions roam.",
  "With milk and oil I never knew, and therefore did I weep, / And I complaind in the mild air, because I fade away.",
  "And I watered it in fears / Night and morning with my tears,",
  "Rising from unrest, / The trembling woman pressed",
  "And dream they see their child / Starved in desert wild.",
  "Then the Parson might preach, and drink, and sing, / And we'd be as happy as birds in the spring;",
  "Thou His image ever see, / Heavenly face that smiles on thee!",
  "Receive each mild spirit, / New worlds to inherit.",
  "And God, like a father, rejoicing to see / His children as pleasant and happy as he,",
  "The sun does arise, / And make happy the skies;",
  "Into a western couch of thunder-cloud; / And thou, a ghost, amid the entombing trees",
  "While I nodded, nearly napping, suddenly there came a tapping, / As of some one gently rapping--rapping at my chamber door.",
  "And Nesace is in her halls again. / From the wild energy of wanton haste",
  "In a night, or in a day, / In a vision or in none,",
  "Then even thy glowing bosom beats withal, / And when old Time my wing did disenthral",
  "Up domes--up spires--up kingly halls-- / Up fanes--up Babylon-like walls--",
  "Richer, far wilder, far diviner visions / Than even the seraph harper, Israfel,",
  "That palpitate like the chill seas / Around the misty Hebrides!",
  "To happy flowers that night--and tree to tree; / Fountains were gushing music as they fell",
  "But, just like any other dream, / Upon the vapor of the dew",
  "But my heart it is brighter / Than all of the many",
  "Hath dwelt, and he where I, / He might not sing so wildly well",
  "Tho' the beings whom thy Nesace, / Thy messenger hath known",
  "What could there be more purely bright / In Truth's day star?",
  "And she prayed to the angels / To keep me from harm--",
  "Pure--as her young example taught: / Why did I leave it, and, adrift,",
  "Nyctanthes too, as sacred as the light / She fears to perfume, perfuming the night:",
  "Thy image may be, / No magic shall sever",
  "Oh! that my young life were a lasting dream! / My spirit not awakening, till the beam",
  "And wing to other worlds another light! / Divulge the secrets of thy embassy",
  "From thy spirit shall they pass / No more--like dew-drops from the grass.",
  "Where an Eidolon, named NIGHT, / On a black throne reigns upright,",
  "A mortal melody, / While a bolder note than this might swell",
  "Which is enduring, so be deep! / Heaven have her in its sacred keep!",
  "Hath drawn from the skies, / Till they glance thro' the shade, and",
  "In there stepped a stately Raven of the saintly days of yore; / Not the least obeisance made he: not an instant stopped or stayed he;",
  "With the last ecstasy of satiate life-- / Beyond that death no immortality--",
  "I mourn not that the desolate / Are happier, sweet, than I,",
  "The playful maziness of art / In old Alberto's daughter;",
  "And, Guy de Vere, hast _thou_ no tear?--weep now or never more! / See! on yon drear and rigid bier low lies thy love, Lenore!",
  "As having fail'd in duty to him, shriek'd / That she but meant to win him back, fell on him",
  "And arms, and so return him to the King. / Come, therefore, leave thy lady lightly, knave.",
  "As Gareth brought him grovelling on his knees, / So many a time he vaulted up again;",
  "The dragon, which our trembling fathers call'd / The God's own son.",
  "Thus the hard old king: / I took my leave, for it was nearly noon:",
  "Thou seemest, but I know thee who thou art. / And now thou goest up to mock the King,",
  "That mock'd him with returning calm, and cried: / \"Storm in the night! for thrice I heard the rain",
  "My mother knows:' and when I asked her 'how,' / 'My fault' she wept 'my fault! and yet not mine;",
  "And Christ the bait to trap his dupe and fool; / Nor deeds of gift, but gifts of grace he forged,",
  "On a sudden the weird seizure and the doubt: / I seemed to move among a world of ghosts;",
  "Truly, ye men of Arthur be but babes.' / A goblet on the board by Balin, bossed",
  "Lived over: lift thine eyes; my doubts are dead, / My haunting sense of hollow shows: the change,",
  "Take thou the truth as thou hast told it me. / For truly as thou sayest, a Fairy King",
  "\"The stars,\" she whispers, \"blindly run; / A web is wov'n across the sky;",
  "And in herself she moaned `Too late, too late!' / Till in the cold wind that foreruns the morn,",
  "The jewels, had let one finger lightly touch / The warm white apple of her throat, replied,",
  "The coming year's great good and varied ills, / And new developments, whatever spark",
  "But thou, thro' ever harrying thy wild beasts-- / Save that to touch a harp, tilt with a lance",
  "'This noble prince who won our earldom back, / So splendid in his acts and his attire,",
  "The old order changeth, yielding place to new; / And we that fight for our fair father Christ,",
  "Not ever would she love; but brooding turn / The book of scorn, till all my flitting chance",
  "And overgrowing them, went on, and found, / Here too, all hushed below the mellow moon,",
  "Sent up an answer, sobbing, `I am thy fool, / And I shall never make thee smile again.'",
  "But here I will disedge it by thy death.' / `Slay then,' he shrieked, `my will is to be slain,'",
  "He looked and found them wanting; and as now / Men weed the white horse on the Berkshire hills",
  "And after went her way across the bridge, / And reached the town, and while the Prince and Earl",
  "'A kitchen-knave, and sent in scorn of me! / Such fight not I, but answer scorn with scorn.",
  "Whatever happens, not to speak to me, / No, not a word!' and Enid was aghast;",
  "The sound of many a heavily-galloping hoof / Smote on her ear, and turning round she saw",
  "Melissa came; for Blanche had gone, but left / Her child among us, willing she should keep",
  "His horns for hunting on the morrow morn. / And when the King petitioned for his leave",
  "He put the self-same query, but the man / Not turning round, nor looking at him, said:",
  "Worshipt, whose lightest whisper moved him more / Than all the rangd reasons of the world.",
  "And she was the fairest of all flesh on earth, / Guinevere, and in her his one delight.",
  "Sir, for ye know that in King Uther's time / The prince and warrior Gorlos, he that held",
  "In a long valley, on one side whereof, / White from the mason's hand, a fortress rose;",
  "In dung and nettles! hiss, snake--I saw him there-- / Let the fox bark, let the wolf yell. Who yells",
  "Better thou and I were lying, hidden from the heart's disgrace, / Roll'd in one another's arms, and silent in a last embrace.",
  "He followed nearer; ruth began to work / Against his anger in him, while he watched",
  "Ride into that new fortress by your town, / White from the mason's hand, then have I sworn",
  "It richer dyed the rose; / The springing lilies, sweetly prest,",
  "The wife slade cannie to her bed, / But ne’er spak mair.",
  "I ne’er could lend on bill or band, / That five per cent. might blest me;",
  "While through the ragged roof and chinky wall, / Chill, o’er his slumbers, piles the drifty heap!",
  "Or pour, with Gray, the moving flow / Warm on the heart.",
  "Buy braw troggin, &c. / Here’s armorial bearings frae the manse o’ Urr;",
  "Wad haud the Lothians three in tackets, / A towmont gude;",
  "Unseen that night. / Amang the brachens, on the brae,",
  "And, all devout, he never sought / To stem the sacred torrent.",
  "WHILE Europe’s eye is fix’d on mighty things, / The fate of Empires and the fall of Kings;",
  "The very name of Douglas blasted, / Thine that inverted glory!",
  "To think how we stood sweatin’, shakin, / An’ p—’d wi’ dread,",
  "Ah! little ken’d thy reverend grannie, / That sark she coft for her wee Nannie,",
  "Some teach to meliorate the plain / With tillage-skill;",
  "O! happy, happy may he be, / That’s dearest to thy bosom:",
  "And port, O port! shine thou a wee, / And THEN ye’ll see him!",
  "Her ancient weed was russet gray, / Her auld Scots bluid was true;",
  "Fient haet o’t wad hae pierc’d the heart / Of a kail-runt.",
  "The rough burr-thistle, spreading wide / Amang the bearded bear,",
  "Wi twa pund Scots (’twas a’ her riches), / Wad ever grac’d a dance of witches!",
  "But hear their absent thoughts o’ ither, / They’re a’ run-deils an’ jads thegither.",
  "The gowdspink, Music’s gayest child, / Shall sweetly join the choir;",
  "And thought his very een enriched; / Even Satan glowered, and fidged fu' fain,",
  "The speedy gleams the darkness swallow’d; / Loud, deep, and lang, the thunder bellow’d:",
  "He was a gash an’ faithfu’ tyke, / As ever lap a sheugh or dyke.",
  "That tremblest at a despot’s nod, / Yet, crouching under the iron rod,",
  "Shall strongly heave my breast, / That I for poor auld Scotland’s sake",
  "First, in the Sexes’ intermix’d connection, / One sacred Right of Woman is, protection.—",
  "But whether she had three or four, / I cou’d na tell.",
  "Wi’ constables-thae blackguard fallows, / An’ sodgers baith;",
  "O Heaven! in evil strait this day I stand / Before my Judge; either to undergo",
  "Unshaken!  Nor yet staid the terror there: / Infernal ghosts and hellish furies round",
  "Home to his mother's house private returned. / THE END",
  "Reason, is free; and Reason he made right, / But bid her well be ware, and still erect;",
  "Of depth immeasurable. Anon they move / In perfect phalanx to the Dorian mood",
  "Down right into the world's first region throws / His flight precipitant, and winds with ease",
  "In Rhodope, where woods and rocks had ears / To rapture, till the savage clamour drowned",
  "A world devote to universal wrack. / No sooner he, with them of man and beast",
  "Not knowing to what land, yet firm believes: / I see him, but thou canst not, with what faith",
  "Just confidence, and native righteousness, / And honour, from about them, naked left",
  "The golden sun, in splendour likest Heaven, / Allured his eye; thither his course he bends",
  "Visits the herds along the twilight meadows, / Helping all urchin blasts, and ill-luck signs",
  "To stop their overgrowth, as inmate guests / Or violence, he of their wicked ways",
  "As only in his arm the moment lay / Of victory:  Deeds of eternal fame",
  "Be fruitful, multiply, and fill the Earth; / Subdue it, and throughout dominion hold",
  "So heavenly love shall outdo hellish hate, / Giving to death, and dying to redeem,",
  "If stone, carbuncle most or chrysolite, / Ruby or topaz, to the twelve that shone",
  "The rest was craggy cliff, that overhung / Still as it rose, impossible to climb.",
  "In Dan, in Judah, and the bordering Tribes, / To all posterity may stand defam'd,",
  "O pity and shame, that they, who to live well / Entered so fair, should turn aside to tread",
  "Though full of pain, this intellectual being, / Those thoughts that wander through eternity,",
  "Aspect he rose, and in his rising seemed / A pillar of state. Deep on his front engraven",
  "No sooner had the Almighty ceased, but all / The multitude of Angels, with a shout",
  "By suffering, and earn rest from labour won, / If so I may attain. -- So both ascend",
  "To undergo eternal punishment?\" / Whereto with speedy words th' Arch-Fiend replied:--",
  "Soft, modest, meek, demure, / Once join'd, the contrary she proves, a thorn",
  "Thy husband; whom to follow thou art bound; / Where he abides, think there thy native soil.",
  "With whose stolen fruit Man once more to delude. / He ceased; and the arch-angelick Power prepared",
  "Their Maker's image, answered Michael, then / Forsook them, when themselves they vilified",
  "The infernal empire, that so near Heaven's door / Triumphal with triumphal act have met,",
  "For council dinners made rare havoc / With Claret, Moselle, Vin-de-Grave, Hock;",
  "Became with old Greek sculpture reconciled. / Already sages laboured to condense",
  "To the big-boned stock of mighty Berold / And, for strong Cotnar, drank French weak wine,",
  "Now, who shall arbitrate? / Ten men love what I hate,",
  "And happed to hear the land's practitioners / Steeped in conceit sublimed by ignorance,",
  "Of Waring!\"--You?  Oh, never star / Was lost here but it rose afar!",
  "Does he paint? he fain would write a poem, / Does he write? he fain would paint a picture,--",
  "And God's own profound / Was above me, and round me the mountains,",
  "And, stooping, made my cheek lie there, / And spread, o'er all, her yellow hair,",
  "Come with a tune he knows so well. / And how your statues' hearts must swell!",
  "\"Egypt's flesh-pots--nay, the drought was better.\" / Oh, the crowd must have emphatic warrant!",
  "With great grass hat and kerchief black, / Who looked up with his kingly throat,",
  "Didst ever behold so lithe a chine? / His cheek hath laps like a fresh-singed swine.",
  "Into their midst I broke: breath served but for \"Persia has come! / Persia bids Athens proffer slaves'-tribute, water and earth;",
  "On a tall mountain, citied to the top, / Crowded with culture!",
  "And out of a convent, at the word, / Came the lady, in time of spring.",
  "Die, and let it drop beside her pillow / Where it lay in place of Rafael's glory,",
  "It saves a model. So! keep looking so-- / My serpentining beauty, rounds on rounds!",
  "But lips where smiles went out and in; / There was no guessing his kith and kin:",
  "What maketh heaven, That maketh hell. / So, as John called now, through the fire amain,",
  "Till God's own smile came out: / That was thy face!",
  "Its petals up; so, here and there / You brush it, till I grow aware",
  "Wood and stream, I knew, I named, rushing past them again, / \"Have ye kept faith, proved mindful of honours we paid you erewhile?",
  "But wait her commands, obey and be dutiful. / Not that, in fact, there was any commanding;",
  "By the hope in those eyes wide and steady, / He was leagues in the desert already",
  "Doubt his word--and moreover, perforce, / For such gifts as no lady could spurn,",
  "That he sat, as I say, with my head just above his vast knees / Which were thrust out each side around me, like oak roots which please",
  "Hornet-prince of the mad wasps' hive, / And clipt of his wings in Paris square,",
  "Of the Piper perked in the market-place, / With a, \"First, if you please, my thousand guilders!\"",
  "None the less he sang out boldly, / Played in time and tune,",
  "The excellent rulers of the races, great discoverers, sailors, / Marble and brass select from them, with pictures, scenes,",
  "I hear the tale of the divine life and bloody death of the beautiful God—the Christ; / I hear the Hindoo teaching his favorite pupil the loves, wars, adages, transmitted safely",
  "For me children, and the begetters of children. / Undrape! you are not guilty to me, nor stale, nor discarded;",
  "Pleasantly and well-suited I walk, / Whither I walk I cannot define, but I know it is good,",
  "In the need of poems, philosophy, politics, manners, engineering, an appropriate native / grand-opera, shipcraft, any craft, he or she is greatest who contributes the greatest",
  "women. / Over that which hinder’d them—over that which retarded—passing impediments large or small,",
  "O Christ! This is mastering me! / In at the conquer’d doors they crowd. I am possess’d.",
  "that / which preceded it,",
  "trowel-handle, / The piles of materials, the mortar on the mortar-boards, and the steady replenishing by",
  "neighbors and / faces,",
  "The orchestra whirls me wider than Uranus flies; / It wrenches such ardors from me, I did not know I possess’d them;",
  "I see the filaments of the news of the wars, deaths, losses, gains, passions, of my race. / I see the long river-stripes of the earth;",
  "run; / The blood of the brawn beloved of time is unconstraint;",
  "He shall be lawless, rude, illiterate—he shall be one condemn’d by others for deeds / done;",
  "pass;) / What is it I interchange so suddenly with strangers?",
  "Not the right only justified—what we call evil also justified. / Forth from their masks, no matter what,",
  "I shall go forth, / I shall traverse The States awhile—but I cannot tell whither or how long;",
  "You average Spiritual Manhood, purpose of all, pois’d on yourself—giving, not taking / law,",
  "A novice beginning, yet experient of myriads of seasons; / Of every hue and caste am I, of every rank and religion;",
  "love-singer, or something else. / All this time, and at all times, wait the words of true poems;",
  "chaste / husband, content after his day’s work.",
  "I inhale great draughts of space; / The east and the west are mine, and the north and the south are mine.",
  "O MAGNET-SOUTH! O glistening, perfumed South! My South! / O quick mettle, rich blood, impulse, and love! Good and evil! O all dear to me!",
  "The sprawl and fulness of babes, the bosoms and heads of women, the folds of their dress, / their style as we pass in the street, the contour of their shape downwards,",
  "Europe to Asia, Africa join’d, and they to the New World; / The lands, geographies, dancing before you, holding a festival garland,",
  "Pick’d sparingly, without noise, by thee, old Ocean—chosen by thee, / Thou Sea, that pickest and cullest the race, in Time, and unitest Nations!",
  "Or behold children at their sports, / Or the admirable sight of the perfect old man, or the perfect old woman,",
  "Nor flutes, nor harps, nor the bugle-calls of camps; / But, to a new rhythmus fitted for thee,",
  "Ah more—infinitely more; / (As George Fox rais’d his warning cry, “Is it this pile of brick and",
  "The head of the money-maker that plotted all day sleeps, / And the enraged and treacherous dispositions—all, all sleep.",
  "And rises lightly from the bed; / Puts on her silken vestments white,",
  "As I myself were there! Nor in this bower, / This little lime-tree bower, have I not mark'd",
  "I have no thought what men they be; / Nor do I know how long it is",
  "Think first, what you ARE ! Call to mind what you WERE ! / I gave you innocence, I gave you hope,",
  "But moss and rarest mistletoe: / She kneels beneath the huge oak tree,",
  "Ne'er tremble in the gale, yet tremble still, / Fann'd by the water-fall! and there my friends",
  "And life is thorny; and youth is vain; / And to be wroth with one we love",
  "That cling and huddle from the cold / In hollow tree or ruin'd fold.",
  "And elmy fields, seems like society-- / Conversing with the mind, and giving it",
  "Because I'd th' ill-fortune his taste to displease, / He turn'd up his nose,",
  "On springy heath, along the hill-top edge, / Wander in gladness, and wind down, perchance,",
  "This the worst superstition, him except / Aught to desire, Supreme Reality!",
  "And still to the tune of Transmogrification-- / Those muttering",
  "And only speckled by the mid-day sun; / Where its slim trunk the ash from rock to rock",
  "Over the threshold of the gate: / Then the lady rose again,",
  "And looked askance at Christabel- / Jesu, Maria, shield her well!",
  "At silent noon, and eve, and early morn, / The Sea's faint murmur. In the open air",
  "Thy smiles I note, sweet early Flower, / That peeping from thy rustic bower",
  "Behold the dark green file of long lank weeds, / That all at once (a most fantastic sight!)",
  "Well, they are gone, and here must I remain, / This lime-tree bower my prison! I have lost",
  "Come bounding and surrounding me, / Come buffeting, astounding me,",
  "Straining dim eyes to catch the invisible sight, / And strong to bear ourselves in patient pain?",
  "To die were surely sweeter than to live, / Though there be nothing new beneath the sun.",
  "And a robin sings / In the holly-bush.",
  "Yet while I love my God the most, I deem / That I can never love you overmuch;",
  "You want to hear it? well: / Only, my secret's mine, and I won't tell.",
  "Think not that I can grudge it, but believe / I do commend you to that nobler grace,",
  "Would lose not Him, but you, must one be lost, / Nor with Lot's wife cast back a faithless look",
  "Brighter than sunniest day that ever shone, / In happy dreams your smile makes day of night.",
  "I have no heart?-Perhaps I have not; / But then you're mad to take offence",
  "Without Whose Will one lily doth not stand, / Nor sparrow fall at his appointed date;",
  "Which owes the other most? my love was long, / And yours one moment seem'd to wax more strong;",
  "A royal cup for Him, my King: / O Jesus, drink of me.",
  "Ah me, but where are now the songs I sang / When life was sweet because you call'd them sweet?",
  "My heart is like a singing bird / Whose nest is in a water'd shoot;",
  "Cast in the fire the perished thing; / Melt and remould it, till it be",
  "Thus am I mine own prison. Everything / Around me free and sunny and at ease:",
  "But only just my fun. / Today's a nipping day, a biting day;",
  "Lo dм che han detto a' dolci amici addio. - Dante / Amor, con quanto sforzo oggi mi vinci! - Petrarca",
  "Your honourable freedom makes me free, / And you companion'd I am not alone.",
  "And all the woe that moved him so / That he gave that bitter cry,",
  "A dear profaner of great mysteries, / An ardent amorous idolater,",
  "Just like a flower: / I remember you started and ran",
  "With careless scythe too near some flower bed, / And cuts the thorny pillar of the rose,",
  "Till thou hast found the old Castalian rill, / Or from the Lesbian waters plucked drowned Sappho's golden quid!",
  "Treads down their brimming golden chalices / Under light feet which were not made for such rude ravages;",
  "Just shook the trembling petals of her lips / And passed into the void, and Venus knew",
  "And crooked shapes of Terror crouched, / In the corners where we lay:",
  "And bitter wine upon a sponge / Was the savour of Remorse.",
  "Five minutes after. / You were always afraid of a shower,",
  "Within another ring, / And was wondering if the man had done",
  "And watched with gaze of dull amaze / The man who had to swing.",
  "With his long crook undid the wattled cotes, / And from the stack a thin blue wreath of smoke",
  "Or was it the rain? / On your hand as it waved adieu",
  "The little fauns have left the hill, / Even the tired daffodil",
  "He does not stare upon the air / Through a little roof of glass:",
  "From the wan mouths that call on bleeding Thammuz all night long. / But when the doves had reached their wonted goal",
  "There lies a long and level stretch of lawn; / The rabbit knows it, and the mountain bee",
  "And seemed to be in some entranced swoon / Till through the open roof above the full and brimming moon",
  "And hoisted sail, and strained the creaking gear, / And bade the pilot head her lustily",
  "\"How long,\" they say, \"how long, O cruel nation, / Will you stand, to move the world, on a child's heart,—",
  "They drop earth's affections, conceive not of woe ? / I think not. Themselves were too lately forgiven",
  "Why had they come to wither there, / Away from their childhood's land?",
  "As almost you could touch them with a hand, / And dared to do it they were so far off",
  "The lord-lieutenant looking down sometimes / From the empyrean to assure their souls",
  "I yield the grave for thy sake, and exchange / My near sweet view of Heaven, for earth with thee!",
  "If we cared for any meadows, it were merely / To drop down in them and sleep.",
  "She has laughed as softly as if she sighed, / She has counted six, and over,",
  "When Venice and Rome keep their new jubilee, / When your flag takes all heaven for its white, green, and red,",
  "First time he kissed me, he but only kissed / The fingers of this hand wherewith I write;",
  "Could we see her face, be sure we should not know her, / For the smile has time for growing in her eyes:",
  "Now he muses deep the meaning of the Heaven-words as they come. / Speak not! he is consecrated---",
  "Floweth outward with increase--- / Dare not bless him! but be blessed by his peace---and go in peace.",
  "Down his dewlaps sloping— / Which he pushed his nose within,",
  "The shell is over-smooth,—and not so much / Will turn the thing called love, aside to hate",
  "They tell me, my dear father. Broader brows / Howbeit, upon a slenderer undergrowth",
  "\"For oh,\" say the children, \"we are weary, / And we cannot run or leap;",
  "Through my obedience. When I answer now, / I drop a grave thought, break from solitude;",
  "Spreading ruin and scattering ban, / Splashing and paddling with hoofs of a goat,",
  "A THOUGHT ay like a flower upon mine heart, / And drew around it other thoughts like bees",
  "Our hearts, our hopes, are all with thee, / Our hearts, our hopes, our prayers, our tears,",
  "Thy shield is the red harvest moon, suspended / So long beneath the heaven's o'er-hanging eaves;",
  "And, spurning with her foot the ground, / With one exulting, joyous bound,",
  "From the wigwam he departed, / Leading with him Laughing Water;",
  "Filled was her heart with love, and the dawn of an opening heaven / Lighted her soul in sleep with the glory of regions celestial.",
  "Many a farewell word and sweet good-night on the door-step / Lingered long in Evangeline's heart, and filled it with gladness.",
  "Sing as they go, and in singing forget they are weary and wayworn, / So with songs on their lips the Acadian peasants descended",
  "Over it the Star of Evening / Melts and trembles through the purple,",
  "But she heeded not the warning, / Heeded not those words of wisdom,",
  "She shall run upon your errands, / Be your starlight, moonlight, firelight,",
  "And they hopped, and sang, and twittered, / Perked and fluttered all their feathers,",
  "What I have missed with what attained, / Little room do I find for pride.",
  "Tremulous leaves, with soft and silver lining, / Buds that open only to decay;",
  "Which, through the ages that have gone before us, / In long reverberations reach our own.",
  "All silently, the little moon / Drops down behind the sky.",
  "The nimble mercury, ere we are aware, / Descends the elastic ladder of the air;",
  "I remember the sea-fight far away, / How it thundered o'er the tide!",
  "Started the sheeted smoke with flashes of flame intermingled. / These things beheld in dismay the crowd on the shore and on shipboard.",
  "Between the dark and the daylight, / When the night is beginning to lower,",
  "And the voice said: 'O Osseo! / O my son, my best beloved!",
  "A wit's a feather, and a chief a rod; / An honest man's the noblest work of God.",
  "And mine, as man, who feel for all mankind. / _F_. You're strangely proud.",
  "Thus, if Eternal Justice rules the ball, / Thus shall your wives, and thus your children fall:",
  "How will our fathers rise up in a rage, / And swear, all shame is lost in George's age!",
  "Look next on greatness; say where greatness lies? / 'Where, but among the heroes and the wise?'",
  "Pour'd o'er the whitening vale their fleecy care, / Fresh as the morn, and as the season fair:",
  "And the press groan'd with licensed blasphemies. / These monsters, critics! with your darts engage,",
  "Are nameless graces which no methods teach, / And which a master-hand alone can reach.",
  "Old Edward's armour beams on Cibber's breast / With laughter, sure, Democritus had died,",
  "Like bees, are humming in my ears. / 'To-morrow my appeal comes on,",
  "In faith and hope the world will disagree, / But all mankind's concern is charity:",
  "Say, where full instinct is th' unerring guide, / What pope or council can they need beside?",
  "Yet still, not heeding what your heart can teach, / You go to church to hear these flatterers preach.",
  "Some play, some eat, some cack against the wall, / And as they crouchen low, for bread and butter call.",
  "Or fish denied (the river yet unthaw'd), / If then plain bread and milk will do the feat,",
  "About one vice, and fall into the other: / Between excess and famine lies a mean;",
  ],
  arabic: [
  "أنا الذي نظر الأعمى إلى أدبي / وأسمعت كلماتي من به صمم",
  "على قدر أهل العزم تأتي العزائم / وتأتي على قدر الكرام المكارم",
  "وما الدهر إلا من رواة قصائدي / إذا قلت شعراً أصبح الدهر منشدا",
  "إذا غامرت في شرف مروم / فلا تقنع بما دون النجوم",
  "ومن يك ذا فم مر مريض / يجد مراً به الماء الزلالا",
  "الخيل والليل والبيداء تعرفني / والسيف والرمح والقرطاس والقلم",
  "لكل امرئ من دهره ما تعودا / وعادة سيف الدولة الطعن في العدا",
  "أعيذها نظرات منك صادقة / أن تحسب الشحم فيمن شحمه ورم",
  "وكم من عائب قولاً صحيحاً / وآفته من الفهم السقيم",
  "يمت بما لا يرى والميت من نحله / لمن لا يرى ما في يديه فضلا",
  "لولا المشقة ساد الناس كلهم / الجود يفقر والإقدام قتال",
  "أزورهم وسواد الليل يشفع لي / وأنثني وبياض الصبح يُغري بي",
  "سيعلم الجمع ممن ضم مجلسنا / بأنني خير من تسعى به قدم",
  "وجاهل ماتت الآداب عنده / وعاش بها للجهل حتى تعثرا",
  "نحن بنو الموتى فما بالنا / نعاف ما لا بد أن نشربا",
  "متى ما أضع عمامتي تعرفوا / بأن سيوف الهند لا تنبو على كرم",
  "هنيئاً لأرباب النعيم نعيمهم / وللعاشق المسكين ما يتجرع",
  "أبلى الهوى بدني بين الهوى ولهي / وكيف أصبح والأشواق تُقلقني",
  "لقد كذب الواشون ما بحت بالهوى / ولا حملت من خشية البين مُضمرا",
  "وإني لمن قوم كأن نفوسهم / بها أنف أن تسكن الجسم داعيا",
  "ذو العقل يشقى في النعيم بعقله / وأخو الجهالة في الشقاوة يَنعم",
  "لا خيل عندك تهديها ولا مال / فليسعد النطق إن لم يسعد الحال",
  "هجرتك لا قلاً مني ولا ملالا / ولكن رأيت الصدق فيك اختلالا",
  "وقد تجهل العينان في الرأس صاحبها / وتعلم اليد من تصافح من يدا",
  "بكتني أخواتي ولم يكبرن أنني / سأغدو كما قالت وإن لم أصدق",
  "أثقل ما يُستطاع حمله / ما يُثقل في القلب لا في اليد",
  "يا دهر ما أغفل الأيام عن رجل / ظلت تحدث عنه بعد ما مضيا",
  "إن كان حظي من وجودك نظرة / فالعين أول موضع للحظوظ",
  "أُحسن ظني بجميع الورى / فلا أرى إنساناً إلا رأيت مزية",
  "تحمل ثقل الأذى إن رمت أن يُحمل / عنك ثقل الجفاء الطويل المضلل",
  "لا تحML حقداً على من أخطأ / فالخطأ من طبع الإنسان في الأرض",
  "كأن البعاد بيننا موت عاجل / يحول بلا إذن بين الأحبة والأحباب",
  "وما في الاختيار شيء يحكم / إلا العهد والوفاء إن عُقد",
  "أعجب الجاهل من حكمة غيره / وعجب الحكيم من جهل ذاته",
  "من رام شرف النفوس صافياً / فليصفح عن العيوب المبصرة",
  "للصبر حدود إذا تجاوزتها / أصبح الصبر جهلاً لا فضيلة",
  "ما كل ما تشتهيه النفس تملكه / لكل نفس نصيب قد كُتب لها",
  "وليس على المرء بأس من ضعف / إذا كان قوياً عند الفزع",
  "في كل قلب جرح قديم يُدار / وكل جريح يدّعي الاحتمالا",
  "من يُعطَ في القسمة الدنيا سعادته / يُحرَم في الآخرة ألف سعيدة",
  "السيف أصدق أنباءً من الكتب / في حده الحد بين الجد واللعب",
  "إقدام عمرو في سماحة حاتم / في حلم أحنف في ذكاء إياس",
  "كذا فليجل الخطب وليفدح الأمر / فليس لعين لم يفض ماؤها عذر",
  "هو الجد حتى تفضل العين واضحاً / إلى موضع العورات أولى المواضع",
  "لقد زدت وجدي بالأراك وربما / تجنيت ظلماً فالمحب يجني",
  "وطول مقام المرء في الحي مخلق / لديباجتيه فاغترب تتجدد",
  "كريم متى أمدحه أمدحه والورى / معي وإذا ما لمته لمته وحدي",
  "ذهب الصبا وتولت الأيام / وغدا الشباب الغض وهو رمام",
  "وطني لو شُغلت بالخلد عنه / نازعتني إليه في الخلد نفسي",
  "ما كل ما يتمناه المرء يدركه / تجري الرياح بما لا تشتهي السفن",
  "أتى هذا الوجود وليس يدري / من أين أتى وأين المنتهى",
  "وإني وإن كنت الأخير زمانه / لآتٍ بما لم تستطعه الأوائل",
  "الناس في غفلة ومن عبرة / تمر أمام عيون الذاهلين",
  "رحمي من الأرض أهل الأرض قاطبة / لست أولى بها منهم ولا هم مني",
  "العيش نوم والمنايا يقظة / والمرء بينهما خيال ساري",
  "الحمد لله لا شريك له / تعالى عن الأنداد والنظراء",
  "وما اليأس إلا ما يظن الجبان / وما العجز إلا ما يعتقد الضعيف",
  "أرى المجد يأبى أن يُنال بسهلة / كما أبت الجوزاء للمتناول",
  "من يغرس الخير يجنه في زمانه / ومن يزرع الشوك يجرح يديه",
  "وإن المرء تحسبه ضعيفاً / إذا لم تعرف نفسه الكريمة",
  "ليس الفتى من يصون عرضه فقط / بل من يصون عرض غيره بعرضه",
  "كل من أصغى لصوت العقل / وجد الطريق إلى الحق",
  "للروح نداء لا يسمعه غير الأصفياء / وللقلب لغة لا يفهمها غير الأحرار",
  "لا تيأسن من فرج بعد شدة / فكم طلعت شمس بعد الظلام",
  "كن خيراً ولا تسل عن الجزاء / فالخير يجلب الخير في كل أوان",
  "ليس العاقل من يعرف الخير / بل من يفعله حين يُدرك",
  "لا يبلغ المجد أقوام ذوو كسل / حتى يكدوا وما في الكد من عار",
  "إذا القوم سادوا بالعطاء فلا تسد / بغير العطاء فالعطاء هو المجد",
  "من للمروءة إن درست وإن أُميت / ذكرها إلا الكرام الأكارم",
  "وما المرء إلا حيث يجعل نفسه / ففي الناس ذو همة وفيهم ذليل",
  ],
  french: [
  "Demain, dès l'aube, à l'heure où blanchit la campagne / Je partirai.",
  "Ceux qui pieusement sont morts pour la patrie / Ont droit qu'à leur cercueil la foule vienne et prie.",
  "La popularité ? c'est la gloire en gros sous. / Un homme sans amour est une nuit sans étoiles.",
  "On résiste à l'invasion des armées / on ne résiste pas à l'invasion des idées.",
  "Aimer, c'est la moitié de croire. / Vivre, c'est commencer à mourir.",
  "Il ne faut pas que la nuit soit trop longue / pour que l'aube soit belle.",
  "Lorsque la femme est bonne, elle est meilleure que l'homme / lorsqu'elle est mauvaise, elle est pire.",
  "La beauté du diable, c'est la jeunesse. / La jeunesse du diable, c'est la beauté.",
  "Le rire, c'est le soleil ; / il chasse l'hiver du visage humain.",
  "Souffrir passe ; avoir souffert ne passe jamais. / La mémoire est le paradis dont on ne peut être chassé.",
  "Les livres sont des amis froids et sûrs. / La musique exprime ce qui ne peut être dit.",
  "La bonté, c'est le sublime de l'humilité. / L'humilité, c'est la dernière des vertus.",
  "Le premier symptôme de l'amour vrai chez un jeune homme / c'est la timidité, chez une jeune fille c'est la hardiesse.",
  "L'art, c'est moi ; la science, c'est nous. / La nature, c'est Dieu visible.",
  "Il n'y a qu'une chose qui soit vraiment merveilleuse / c'est la nuit au-dessus de l'abîme.",
  "La tristesse est une muraille entre deux jardins. / Le bonheur est une fleur qui pousse sur la muraille.",
  "La vie est une fleur dont l'amour est le miel. / La mort est une porte qui ne s'ouvre que de l'intérieur.",
  "Quand deux êtres s'aimaient si fort autrefois / ils se rencontrent avec un visage d'étrangers.",
  "Un soupir dit plus que mille paroles / un regard dit plus que mille soupirs.",
  "Les grandes pensées viennent du cœur, / et le cœur n'a pas besoin de traducteur.",
  "Mon enfant, ma sœur, / Songe à la douceur d'aller là-bas vivre ensemble.",
  "Je suis la plaie et le couteau ! / Je suis le soufflet et la joue !",
  "Hypocrite lecteur, — mon semblable, — mon frère ! / Toi qui fais semblant de lire et penses à autre chose.",
  "La Nature est un temple où de vivants piliers / Laissent parfois sortir de confuses paroles.",
  "Tout est abîme, — action, désir, rêve, / Parole ! et sur mon poil qui tout droit se relève.",
  "O Mort, vieux capitaine, il est temps ! levons l'ancre ! / Ce pays nous ennuie, ô Mort ! Appareillons !",
  "Sois sage, ô ma Douleur, et tiens-toi plus tranquille. / Tu réclamais le Soir ; il descend ; le voici.",
  "Nous voulons, tant ce feu nous brûle le cerveau, / Plonger au fond du gouffre, Enfer ou Ciel, qu'importe ?",
  "Là tout n'est qu'ordre et beauté, / Luxe, calme et volupté.",
  "La musique souvent me prend comme une mer ! / Vers ma pâle étoile, sous un plafond de brume.",
  "Je pense à la négresse, amaigrie et phtisique, / Piétinant dans la boue, et cherchant, l'œil hagard.",
  "Ô toi que j'eusse aimée, ô toi qui le savais ! / Mon cœur est un palais flétri par la cohue.",
  "Le Poète est semblable au prince des nuées / Qui hante la tempête et se rit de l'archer.",
  "J'ai plus de souvenirs que si j'avais mille ans. / Un gros meuble à tiroirs encombré de bilans.",
  "Tout homme bien portant peut se passer de manger / pendant deux jours ; de poésie jamais.",
  "Quel est ce noir manoir ? C'est le mien. Roméo ? / Non. Je suis le Vampire, fils du Crépuscule.",
  "Pluvieuse, irritée contre la ville entière, / De son urne à grands flots verse un froid ténébreux.",
  "Les parfums, les couleurs et les sons se répondent. / Il est des parfums frais comme des chairs d'enfants.",
  "Homme libre, toujours tu chériras la mer ! / La mer est ton miroir ; tu contemples ton âme.",
  "Je hais le mouvement qui déplace les lignes, / Et jamais je ne pleure et jamais je ne ris.",
  "Les sanglots longs / Des violons de l'automne.",
  "Il pleure dans mon cœur / Comme il pleut sur la ville.",
  "Le ciel est, par-dessus le toit, / Si bleu, si calme !",
  "De la musique avant toute chose, / Et pour cela préfère l'Impair.",
  "Mon Dieu, mon Dieu, la vie est là, / Simple et tranquille.",
  "Je suis venu, calme orphelin, / Riche de mes seuls yeux tranquilles,",
  "O triste, triste était mon âme / À cause, à cause d'une femme.",
  "Dans l'interminable Ennui de la plaine / La neige incertaine Luit comme du sable.",
  "Voici des fruits, des fleurs, des feuilles et des branches / Et puis voici mon cœur qui ne bat que pour vous.",
  "Le son du cor s'afflige vers les bois / D'une douleur on veut croire orpheline.",
  "Souvenir, souvenir, que me veux-tu ? L'automne / Faisait voler la grive à travers l'air atone.",
  "Qui dira les torts de La Femme ? / Rien, sinon qu'il vaut mieux l'aimer.",
  "Gaspard Hauser chante : / Je suis venu, calme orphelin.",
  "Le vent de l'autre nuit a jeté bas l'Amour / Qui, dans un coin obscur de mon cœur, cherchait l'ombre.",
  "J'ai perdu ma vie et je sais bien / Que tout le blâme en est à moi seul.",
  "On n'est pas sérieux, quand on a dix-sept ans. / Un beau soir, foin des bocks et de la limonade.",
  "Je m'en allais, les poings dans mes poches crevées ; / Mon paletot aussi devenait idéal.",
  "O saisons, ô châteaux ! / Quelle âme est sans défauts ?",
  "Dans la nuit, l'orage s'allume / Et le cœur du poète vibre.",
  "Noir dans la neige et dans la brume / Au grand soupirail qui s'allume.",
  "J'ai embrassé l'aube d'été. / Rien ne bougeait encore au front des palais.",
  "Je est un autre. / C'est faux de dire : Je pense.",
  "Le Bateau ivre sur les flots / Ne gouverne plus son destin.",
  "Ma Bohème allait, les mains dans les poches / Totalement défoncées.",
  "Comme je descendais des Fleuves impassibles / Je ne me sentis plus guidé par les haleurs.",
  "L'aube exaltée ainsi qu'un peuple de colombes / Et j'ai vu quelquefois ce que l'homme a cru voir !",
  "Voici le temps des Assassins. / Voici venir les temps où vibrants sur leur tige.",
  "Elle est retrouvée. Quoi ? — L'Éternité. / C'est la mer allée Avec le soleil.",
  "Par les soirs bleus d'été, j'irai dans les sentiers / Picoté par les blés, fouler l'herbe menue.",
  "J'écrivais des silences, des nuits, je notais l'inexprimable. / Je fixais des vertiges.",
  "Ô temps ! suspends ton vol, et vous, heures propices ! / Suspendez votre cours.",
  "Ainsi, toujours poussés vers de nouveaux rivages, / Dans la nuit éternelle emportés sans retour.",
  "Un seul être vous manque, et tout est dépeuplé ! / Que le jour recommence et que le jour finisse.",
  "Dieu, pour le concevoir, a fait l'intelligence; / sous la nature enfin découvrir sa puissance.",
  "Le monde est le livre de Dieu. / Chaque astre est une lettre de flamme.",
  "Ô lac ! l'année à peine a fini sa carrière / Et près des flots chéris qu'elle devait revoir.",
  "L'homme est un dieu tombé qui se souvient des cieux. / La terre est pour lui l'exil.",
  "Repose-toi, mon âme, en ce dernier asile / Ainsi qu'un voyageur qui, le cœur plein d'espoir.",
  "Laissons le temps au temps, / et laissons faire à Dieu.",
  "La poésie est la prose des grandes âmes. / La musique est la langue des anges.",
  "Mignonne, allons voir si la rose / Qui ce matin avoit desclose.",
  "Je vous envoie un bouquet que ma main / Vient de trier de ces fleurs épanies.",
  "Quand vous serez bien vieille, au soir à la chandelle / Assise auprès du feu, dévidant et filant.",
  "Vivez, si m'en croyez, n'attendez à demain : / Cueillez dès aujourd'hui les roses de la vie.",
  "Marie, levez-vous, ma jeune paresseuse : / Jà la gaie alouette au ciel a fredonné.",
  "Comme on voit sur la branche au mois de mai la rose / En sa belle jeunesse, en sa première fleur.",
  "Je plantai en mon jardin un jeune rosier / Que j'ai vu si beau, si gai, si florissant.",
  "L'homme est bien sot, qui aime sans retour / Son labeur, sa peine, et son amour.",
  "Nature ornant Cassandre qui devoit / De sa douceur forcer les plus rebelles.",
  "Bonjour mon cœur, bonjour ma douce vie / Bonjour mon œil, bonjour ma chère amie.",
  ],
  german: [
  "Über allen Gipfeln ist Ruh, / In allen Wipfeln spürest du kaum einen Hauch.",
  "Wer nie sein Brot mit Tränen aß, / Wer nie die kummervollen Nächte auf seinem Bette weinend saß.",
  "Du hast Diamanten und Perlen, / Hast alles, was Menschenbegehr.",
  "Es irrt der Mensch, solang er strebt. / Das ist der Weisheit letzter Schluss.",
  "Wer immer strebend sich bemüht, / Den können wir erlösen.",
  "Kennst du das Land, wo die Zitronen blühn, / Im dunkeln Laub die Gold-Orangen glühn.",
  "Zwei Seelen wohnen, ach! in meiner Brust, / Die eine will sich von der andern trennen.",
  "Das Beste, was wir von der Geschichte haben, / ist der Enthusiasmus, den sie erregt.",
  "Man muss das Mögliche mit Liebe umfassen, / das Unmögliche mit Gleichmut ertragen.",
  "Grau, teurer Freund, ist alle Theorie, / Und grün des Lebens goldner Baum.",
  "Ich bin von je der Ordnung Freund gewesen. / Nichts wider die Natur, das gilt des Lebens Ruhm.",
  "Die Kunst ist eine Vermittlerin des Unaussprechlichen. / Ob sie gleich vielerlei sagen kann.",
  "Wer sich der Einsamkeit ergibt, / ach! der ist bald allein.",
  "Es ist nicht genug zu wissen, man muss auch anwenden; / Es ist nicht genug zu wollen, man muss auch tun.",
  "Der Mensch erfährt, er sei auch wer er mag, / Ein letztes Glück und einen letzten Tag.",
  "Was du ererbt von deinen Vätern hast, / erwirb es, um es zu besitzen.",
  "Die Botschaft hör ich wohl, allein mir fehlt der Glaube. / Das Wunder ist des Glaubens liebstes Kind.",
  "Gut und edel sei der Mensch, / hilfreich und gut.",
  "In der Kunst ist das Beste gut genug. / Das Beste geben ist des Künstlers pflicht.",
  "Wer anderen eine Grube gräbt, fällt selbst hinein. / Das sagt sich leicht, doch wer befolgt es?",
  "Der Augenblick ist Ewigkeit. / Wenn du ihn recht genieußt.",
  "Beschränkung zeigt den Meister, / Und das Gesetz nur kann uns Freiheit geben.",
  "Im Anfang war die Tat. / Nicht Wort, sondern Tat.",
  "Welche Regierung die beste sei? / Diejenige, die uns lehrt, uns selbst zu regieren.",
  "Denn all mein Leib und Leben / ist dein allein gegeben.",
  "Mit dem Genius steht die Natur im ewigen Bunde. / Was der eine verspricht, leistet die andere gewiss.",
  "Freude, schöner Götterfunken, / Tochter aus Elysium.",
  "Alle Menschen werden Brüder, / wo dein sanfter Flügel weilt.",
  "Was ist die Mehrheit? Mehrheit ist der Unsinn; / Verstand ist stets bei wen'gen nur gewesen.",
  "Ernst ist das Leben, heiter ist die Kunst. / So bleib dem Lebendigen hold.",
  "Der Starke ist am mächtigsten allein. / Der Schwache bedarf der Gesellschaft.",
  "Dem Manne ziemt die Freiheit, / dem Weibe die Tugend.",
  "Ich bin dein Schwert und deine Lanze! / Ich bin dein Schild und dein Geharnisch.",
  "Die Weltgeschichte ist das Weltgericht. / Jeder trägt was er getan.",
  "Wer nichts für andere tut, / tut nichts für sich.",
  "Geschichte ist nicht nur das, was war, / sondern was immer wieder ist.",
  "Das eben ist der Fluch der bösen Tat, / daß sie fortzeugend immer Böses muß gebären.",
  "Ans Vaterland, ans teure, schließ dich an, / das halte fest mit deinem ganzen Herzen.",
  "Nur der verdient die Freiheit wie das Leben, / der täglich sie erobern muss.",
  "Drum prüfe, wer sich ewig bindet, / ob sich das Herz zum Herzen findet.",
  "Soll seine Pflicht ein Jeder tun? / Dann muß sein Lohn ihm auch werden.",
  "Was man in der Jugend wünscht, / hat man im Alter die Fülle.",
  "Der Mensch spielt nur, wo er in voller Bedeutung des Worts Mensch ist / und er ist nur da ganz Mensch, wo er spielt.",
  "Edel sei der Mensch, hilfreich und gut! / Denn das allein unterscheidet ihn von allen Wesen.",
  "Das ist die Blindheit der Verblendeten: / sie fliehn die Wahrheit, die sie doch nicht meiden kann.",
  "Ich weiß nicht, was soll es bedeuten, / daß ich so traurig bin.",
  "Ein Fichtenbaum steht einsam / im Norden auf kahler Höh.",
  "Die Lotusblume ängstigt / sich vor der Sonne Pracht.",
  "Du bist wie eine Blume / so hold und schön und rein.",
  "Leise zieht durch mein Gemüt / liebliches Geläute.",
  "Ich hatte einst ein schönes Vaterland. / Die Eiche wuchs dort hoch, die Veilchen nickten sanft.",
  "Denk ich an Deutschland in der Nacht, / dann bin ich um den Schlaf gebracht.",
  "Das Herz ist mir schwer; / komm, laß uns wandern ins Tal.",
  "Mir träumte von einem Königskind, / mit nassen, blassen Wangen.",
  "Die Jahre kommen und gehen, / Geschlechter steigen ins Grab.",
  "Brich aus in lauten Klagen, / Du düstere Nachtmusik.",
  "Ich grolle nicht, und wenn das Herz auch bricht, / Ewig verlornes Lieb! ich grolle nicht.",
  "Anfangs wollt ich fast verzagen / und ich glaubt', ich trüg es nie.",
  "Das ist ein Flöten und Geigen, / Trompeten schmettern darein.",
  "Wenn ich an deinem Hause / des Morgens vorübergeh.",
  "Vergiftet sind meine Lieder; / wie könnt es anders sein?",
  "Es liegt der heiße Sommer / auf deinen Wängelein.",
  "Wir haben viel füreinander gefühlt / und dennoch uns sehr wenig gesagt.",
  "In mein gar zu dunkles Leben / strahltest du, ein goldner Stern.",
  "Die alten bösen Lieder, / die Träume schlimm und arg.",
  "Wer, wenn ich schriee, hörte mich denn aus der Engel Ordnungen? / Die Schönheit ist nichts als des Schrecklichen Anfang.",
  "Ich lebe mein Leben in wachsenden Ringen, / die sich über die Dinge ziehn.",
  "Ich glaube an alles noch nie Gesagte. / Ich will meine frömmsten Gefühle befrein.",
  "Es gibt Momente, wo einem das Vergängliche / so nahekommt wie ein Atemzug.",
  "Wer hat uns also umgedreht, daß wir, / was wir auch tun, in jener Haltung sind von einem.",
  "Der Herbst ist wieder / in den Feldern groß.",
  "Wer jetzt kein Haus hat, baut sich keines mehr. / Wer jetzt allein ist, wird es lange bleiben.",
  "Du musst dein Leben ändern. / Das Schöne ist nichts als des Schrecklichen Anfang.",
  "Ich lebe gern: vielleicht ist morgen tot. / Ich sterbe gern: vielleicht ist morgen neu.",
  "Einmal, am Rand eines Weges, stand er stille / und sah lange in die Ferne.",
  "Alles wird wieder groß sein und gewaltig. / Die Erde gärt und kann nicht stille stehn.",
  "Wo aber Gefahr ist, wächst das Rettende auch. / Das ist der Weisheit letzter Schluss.",
  "Schönheit ist nicht mehr. / Die Götter sind entflohen.",
  "Wie Harfentöne, kommt der Frühling. / Er ruft: Ich bin's, ich bin's!",
  "Voll Verdienst, doch dichterisch wohnet der Mensch auf dieser Erde. / Was bleibet aber, stiften die Dichter.",
  "Im heiligen Dunkel der Nacht findet der Dichter, / was er am Tage nicht erkennen kann.",
  "Der Rhein sucht sich seinen Weg / durch Felsen und Wälder.",
  "An den Ufern des Rheins und an den Hügeln des Mains / darf ich träumen.",
  "Nicht Gedachtes ist das Denken, / sondern Denken ist das Gedachte.",
  "So bin ich. Du aber bist mehr als ich: / du bist die Erde selbst.",
  "Einst hab ich die Muse gefragt, und sie / Antwortete mir: Geh, geh und diene!",
  "Über die Heide hallet mein Schritt; / Dumpf aus der Erde wandert es mit.",
  "Wir saßen am Fischerhause / und schauten nach See hinaus.",
  "Die Nacht war nur ein mattes Grau. / Die Stille war der einzige Laut.",
  "Grau, liebe Brut, die ihr durch meine Träume fleugt! / Ihr Nebel, die ihr über Wasser lauft.",
  ],
  spanish: [
  "Puedo escribir los versos más tristes esta noche. / Quiero hacer algo contigo esta noche.",
  "Te quiero tal como eres. / Con tu amor me alcanza.",
  "Es tan corto el amor y tan largo el olvido. / La noche está estrellada y tiemblan los astros.",
  "Dos amantes felices hacen un solo pan. / Con un solo beso nace el mundo.",
  "Amor es tan corto, olvido es tan largo. / Hoy la quise, y a veces ella también me quería.",
  "Mujer, yo hubiera sido tu hijo, / por beberte la leche de los senos.",
  "Cuántas veces miraste al cielo buscando / lo que yo llevaba quieto en mi pecho.",
  "¿Qué es la poesía? Es una isla rodeada de cielo. / Es la tristeza que hace bellas a las cosas.",
  "La vida es lo que sucede mientras estás ocupado / haciendo otros planes.",
  "Si no viviste lo que soñaste / no ames lo que nunca fue.",
  "Arderás en mi hogar, en mis brazos, fundida / como la nieve junto a las brasas rojas.",
  "La luna vive en el forro de tu piel. / La noche tuya tiene tanto espacio.",
  "Quiero hacer contigo lo que la primavera hace con los cerezos. / Quiero que sepas una cosa.",
  "Me gustas cuando callas porque estás como ausente. / Y me oyes desde lejos y mi voz no te toca.",
  "Amo el amor de los marineros que besan y se van. / Dejan una promesa que no han de cumplir.",
  "Verde que te quiero verde. / Verde viento. Verdes ramas.",
  "A las cinco de la tarde. / Eran las cinco en punto de la tarde.",
  "Que yo me muera mirando tus ojos grises. / Que me doblen las flores en la mañana.",
  "La luna vino a la fragua / con su polisón de nardos.",
  "Por las ramas del laurel / vi dos palomas oscuras.",
  "Se ha puesto el sol. / Suenan las campanas.",
  "En el principio era el verbo. / Y el verbo estaba con Dios. Y el verbo era Dios.",
  "Volver a querer a alguien / Es volver a nacer.",
  "No hay noche que al día no siga. / No hay pena que al gozo no siga.",
  "Córdoba. Lejana y sola. / Jaca negra, luna grande.",
  "Añoranza, brasa roja. / La noche se abre impasible.",
  "Bodas de sangre, en la mañana / brillan las cuchillas del amor.",
  "La muerte entra y sale / de la taberna.",
  "New York, New York. / Cieno, alambre, brisa, espadaña.",
  "Me quedaré en esta tierra / esperando tu regreso.",
  "Caminante, son tus huellas el camino y nada más. / Caminante, no hay camino, se hace camino al andar.",
  "Al andar se hace camino y al volver la vista atrás / se ve la senda que nunca se ha de volver a pisar.",
  "Nuestras horas son minutos / cuando esperamos saber.",
  "Ayer soñé que veía a Dios y que a Dios hablaba; / y soñé que Dios me oía... después soñé que soñaba.",
  "De diez cabezas, nueve embisten y una piensa. / Nunca olvides, amigo, que la razón o es de todos o no es de nadie.",
  "Yo voy soñando caminos de la tarde. / ¡Las colinas doradas, los verdes pinos!",
  "Bajo las ramas del olmo en el huerto / ha brotado la paz.",
  "He andado muchos caminos. / He abierto muchas veredas.",
  "El ojo que ves no es ojo porque tú lo veas / es ojo porque te ve.",
  "La primavera ha venido. / Nadie sabe cómo ha sido.",
  "Miré los muros de la patria mía, / si un tiempo fuertes, ya desmoronados.",
  "Polvo serán, mas polvo enamorado. / Cerrar podrá mis ojos la postrera sombra.",
  "Ayer se fue; Mañana no ha llegado; / Hoy se está yendo sin parar un punto.",
  "Es hielo abrasador, es fuego helado, / es herida que duele y no se siente.",
  "Es un no querer querer queriendo, / es un andar solitario acompañado.",
  "Madre, yo al oro me humillo; / él es mi amante y mi amado.",
  "Vivir es caminar breve jornada / y muerte viva es, Lico, nuestra vida.",
  "La brevedad de la vida, / Lico, no te desesperes.",
  "Que no me conocéis me tiene absorto / si véis que soy mortal y me miráis.",
  "Bien te veo correr, tiempo ligero, / cual nave por el mar que el viento lleva.",
  ],
  russian: [
  "Ya vas lyubil: lyubov' yeshcho, byt' mozhet, / V dushe moyey ugasla ne sovsem.",
  "Ya pomnyu chudnoye mgnovenye: / Predo mnoy yavilas' ty.",
  "Buryoyu nebo mrakhoyu / Vikhrí snezhnyye krútya.",
  "Zimniy vecher v komnate / Svechka gorit na stole.",
  "Volny i lyudi mezhdu soboyu / Vstrechayutsya i razluchayutsya.",
  "Vykhozhu odin ya na dorogu; / Skvoz' tuman kremenistyy put' blesht it.",
  "Я вас любил так искренно — так нежно / Как дай вам бог любимой быть другим.",
  "Не дай мне бог сойти с ума. / Нет, легче посох и сума.",
  "Что в имени тебе моём? / Оно умрёт, как шум печальный.",
  "Мороз и солнце; день чудесный! / Ещё ты дремлешь, друг прелестный.",
  "Унылая пора! Очей очарованье! / Приятна мне твоя прощальная краса.",
  "Я помню чудное мгновенье: / Передо мной явилась ты.",
  "Пора, мой друг, пора! покоя сердце просит. / Летят за днями дни, и каждый час уносит.",
  "Я жить хочу, чтоб мыслить и страдать. / И буду жить — вот, знаю, что буду.",
  "С добрым утром — блещет снег. / Солнце светит за окном.",
  "Белеет парус одинокой / В тумане моря голубом.",
  "Что ищет он в стране далёкой? / Что кинул он в краю родном?",
  "Выхожу один я на дорогу; / Сквозь туман кремнистый путь блестит.",
  "Ночь тиха. Пустыня внемлет Богу, / И звезда с звездою говорит.",
  "Я не унижусь пред тобою; / Ни твой привет, ни твой укор.",
  "На севере диком стоит одиноко / На голой вершине сосна.",
  "И скучно, и грустно, и некому руку подать / В минуту душевной невзгоды.",
  "Гляжу на будущность с боязнью, / Гляжу на прошлое с тоской.",
  "Мне грустно потому, что я тебя люблю. / И знаю: молодость цветущую твою.",
  "Есть речи — значенье темно иль ничтожно, / Но им без волненья внимать невозможно.",
  "Я научилась просто, мудро жить, / Смотреть на небо и молиться Богу.",
  "Сжала руки под тёмной вуалью… / «Отчего ты сегодня бледна?»",
  "Мне голос был. Он звал утешно, / Он говорил: «Иди сюда».",
  "Та девочка, что прихромала / И поглядела исподлобья.",
  "Муж в могиле, сын в тюрьме, / Помолитесь обо мне.",
  "Эта встреча никем не воспета, / И без песен печаль улеглась.",
  "Горят твои ладони, / В ушах пасхальный звон.",
  "Не с теми я, кто бросил землю / На растерзание врагам.",
  "Подушка уже горяча / С обеих сторон.",
  "Я слышу иволги всегда печальный голос / И лета пышного приветствую ущерб.",
  "Умом Россию не понять, / Аршином общим не измерить.",
  "О, как убийственно мы любим! / Как в буйной слепоте страстей.",
  "Молчи, скрывайся и таи / И чувства, и мечты свои.",
  "Нам не дано предугадать, / Как слово наше отзовётся.",
  "Не то, что мните вы, природа: / Не слепок, не бездушный лик.",
  "Чему бы жизнь нас ни учила — / Но сердце верит в чудеса.",
  "Певучесть есть в морских волнах, / Гармония в стихийных спорах.",
  "Есть в осени первоначальной / Короткая, но дивная пора.",
  "Блажен, кто посетил сей мир / В его минуты роковые!",
  "День вечереет, ночь близка, / Длинней с горы ложится тень.",
  "Ночь, улица, фонарь, аптека, / Бессмысленный и тусклый свет.",
  "Река раскинулась. Течёт, грустит лениво / И моет берега.",
  "О, весна без конца и без краю — / Без конца и без краю мечта!",
  "Я послал тебе чёрную розу в бокале / Золотого, как небо, аи.",
  "Девушка пела в церковном хоре / О всех усталых в чужом краю.",
  ],
  italian: [
  "Nel mezzo del cammin di nostra vita / mi ritrovai per una selva oscura.",
  "Lasciate ogni speranza, voi ch'entrate. / Qui si convien lasciare ogni sospetto.",
  "Amor, ch'a nullo amato amar perdona, / mi prese del costui piacer sì forte.",
  "La bocca mi baciò tutto tremante. / Galeotto fu il libro e chi lo scrisse.",
  "Nessun maggior dolore / che ricordarsi del tempo felice.",
  "E quindi uscimmo a riveder le stelle. / Era già l'ora che volge il disio.",
  "Considerate la vostra semenza: / fatti non foste a viver come bruti.",
  "L'amor che move il sole e l'altre stelle. / In his will is our peace.",
  "Pape Satàn, pape Satàn aleppe! / Così Pluto con la voce chioccia.",
  "In la sua volontade è nostra pace: / ella è quel mare al qual tutto si move.",
  "Vuolsi così colà dove si puote / ciò che si vuole, e più non dimandare.",
  "Dinanzi a me non fuor cose create / se non etterne, e io etterno duro.",
  "Per me si va nella città dolente, / per me si va ne l'etterno dolore.",
  "Midway this way of life we're bound upon / I woke to find myself in a dark wood.",
  "Love, that releases no beloved from loving / took hold of me so strongly through his beauty.",
  "Erano i capei d'oro a l'aura sparsi, / Che 'n mille dolci nodi gli avolgea.",
  "Pace non trovo e non ho da far guerra; / e temo e spero, e ardo e son un ghiaccio.",
  "Solo et pensoso i più deserti campi / vo mesurando a passi tardi et lenti.",
  "Chiare, fresche et dolci acque, / ove le belle membra pose colei.",
  "Benedetto sia 'l giorno, e 'l mese, et l'anno, / et la stagione, e 'l tempo, et l'ora, e 'l punto.",
  "Zefiro torna, e 'l bel tempo rimena, / e i fiori et l'erbe, sua dolce famiglia.",
  "Se voi poteste per turbati segni / per foschi giorni et per notti senz'alba.",
  "Voi ch'ascoltate in rime sparse il suono / di quei sospiri ond'io nudriva 'l core.",
  "La vita fugge, e non s'arresta un'ora / e la morte vien dietro a gran giornate.",
  "I' vidi in terra angelici costumi / e celeste bellezza in mortale velo.",
  "Itene al cantar mio soavi accenti, / e morte, e 'l cielo, e la fortuna accuso.",
  "L'aura che 'l verde lauro et l'aureo crine / soavemente sospirando move.",
  "Quant'occhi ha il mondo, tanti ne la scorta / d'Amor, che l'alma mia guidar vi mena.",
  "La gola e 'l sonno et l'otiose piume / hanno del mondo ogni vertù sbandita.",
  "S'amor non è, che dunque è quel ch'io sento? / Ma s'egli è amor, per Dio, che cosa et quale?",
  "Sempre caro mi fu quest'ermo colle, / e questa siepe, che da tanta parte.",
  "E il naufragar m'è dolce in questo mare. / Così tra questa immensità s'annega il pensier mio.",
  "O graziosa luna, io mi rammento / che, or volge l'anno, sovra questo colle.",
  "Che fai tu, luna, in ciel? dimmi, che fai, / silenziosa luna?",
  "A Silvia rimembravi / quel tempo della tua vita mortale.",
  "Questo è quel mondo? questi / i diletti, l'amor, l'opre, gli eventi.",
  "Ermo colle, erta balza, / dov'è che 'l mio pensiero.",
  "La donzelletta vien dalla campagna / in sul calar del sole.",
  "Passata è la tempesta: / odo augelli far festa.",
  "Che bella cosa / una giornata di sole.",
  "All'ombra de' cipressi e dentro l'urne / confortate di pianto è forse il sonno.",
  "Né più mai toccherò le sacre sponde / ove il mio corpo fanciulletto giacque.",
  "Un dì, s'io non andrò sempre fuggendo / di gente in gente, me vedrai seduto.",
  "Solcata ho fronte, occhi incavati intenti, / crin fulvo, emunte guance, ardito aspetto.",
  "Il di' morì: fui solo; e quale immago / mi richia muovi al cor.",
  "Traverso il verde de la piaggia e d'alto / brillava il sol su la città lontana.",
  "O primavera, gioventù dell'anno; / o gioventù primaverile della vita.",
  "Alzo gli occhi al cielo nitido / e vedo le stelle tremano.",
  "San Martino: la nebbia agli irti colli / piovigginando sale.",
  "La nebbia agl'irti colli / piovigginando sale, e sotto il maestrale.",
  ],
};

export function getWorldCoverTexts(category: WorldCoverCategory): string[] {
  return WORLD_COVER_TEXTS[category];
}

export function getRandomWorldCoverText(category: WorldCoverCategory): string {
  const texts = WORLD_COVER_TEXTS[category];
  return texts[Math.floor(Math.random() * texts.length)];
}


